//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gds.lastschrifttyp.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="gds.lastschrifttyp">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="FNAL"/>
 *     &lt;enumeration value="FRST"/>
 *     &lt;enumeration value="OOFF"/>
 *     &lt;enumeration value="RCUR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "gds.lastschrifttyp")
@XmlEnum
public enum GdsLastschrifttyp {

    FNAL,
    FRST,
    OOFF,
    RCUR;

    public String value() {
        return name();
    }

    public static GdsLastschrifttyp fromValue(String v) {
        return valueOf(v);
    }

}
