//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="info" type="{http://www.xjustiz.de}Type.INSO.IRI.ReferenzDaten" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ergebnistabelle" type="{http://www.xjustiz.de}Type.INSO.IRI.Ergebnistabelle" minOccurs="0"/>
 *                   &lt;element name="kontext" type="{http://www.xjustiz.de}Type.INSO.IRI.Basiskontext"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.inso.iri.einfacheSuche.antwort.0300020")
public class NachrichtInsoIriEinfacheSucheAntwort0300020 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected NachrichtInsoIriEinfacheSucheAntwort0300020 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtInsoIriEinfacheSucheAntwort0300020 .Fachdaten }
     *     
     */
    public NachrichtInsoIriEinfacheSucheAntwort0300020 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtInsoIriEinfacheSucheAntwort0300020 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtInsoIriEinfacheSucheAntwort0300020 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="info" type="{http://www.xjustiz.de}Type.INSO.IRI.ReferenzDaten" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ergebnistabelle" type="{http://www.xjustiz.de}Type.INSO.IRI.Ergebnistabelle" minOccurs="0"/>
     *         &lt;element name="kontext" type="{http://www.xjustiz.de}Type.INSO.IRI.Basiskontext"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "info",
        "ergebnistabelle",
        "kontext"
    })
    public static class Fachdaten {

        protected List<TypeINSOIRIReferenzDaten> info;
        protected TypeINSOIRIErgebnistabelle ergebnistabelle;
        @XmlElement(required = true)
        protected TypeINSOIRIBasiskontext kontext;

        /**
         * Gets the value of the info property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the info property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeINSOIRIReferenzDaten }
         * 
         * 
         */
        public List<TypeINSOIRIReferenzDaten> getInfo() {
            if (info == null) {
                info = new ArrayList<TypeINSOIRIReferenzDaten>();
            }
            return this.info;
        }

        /**
         * Gets the value of the ergebnistabelle property.
         * 
         * @return
         *     possible object is
         *     {@link TypeINSOIRIErgebnistabelle }
         *     
         */
        public TypeINSOIRIErgebnistabelle getErgebnistabelle() {
            return ergebnistabelle;
        }

        /**
         * Sets the value of the ergebnistabelle property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeINSOIRIErgebnistabelle }
         *     
         */
        public void setErgebnistabelle(TypeINSOIRIErgebnistabelle value) {
            this.ergebnistabelle = value;
        }

        /**
         * Gets the value of the kontext property.
         * 
         * @return
         *     possible object is
         *     {@link TypeINSOIRIBasiskontext }
         *     
         */
        public TypeINSOIRIBasiskontext getKontext() {
            return kontext;
        }

        /**
         * Sets the value of the kontext property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeINSOIRIBasiskontext }
         *     
         */
        public void setKontext(TypeINSOIRIBasiskontext value) {
            this.kontext = value;
        }

    }

}
