//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="geschaeftszeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                   &lt;element name="suche">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;sequence>
 *                               &lt;element name="nachname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
 *                               &lt;element name="nachname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                               &lt;element name="vorname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
 *                               &lt;element name="vorname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                               &lt;element name="geburtsname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
 *                               &lt;element name="geburtsname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                               &lt;element name="geburtsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                               &lt;element name="geburtsdatum.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/sequence>
 *                           &lt;attribute name="menge" type="{http://www.w3.org/2001/XMLSchema}long" default="50" />
 *                           &lt;attribute name="versatz" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.zvr.sucheRegistrierung.input.1000008")
public class NachrichtZvrSucheRegistrierungInput1000008 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten }
     *     
     */
    public NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="geschaeftszeichen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *         &lt;element name="suche">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;sequence>
     *                     &lt;element name="nachname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
     *                     &lt;element name="nachname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                     &lt;element name="vorname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
     *                     &lt;element name="vorname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                     &lt;element name="geburtsname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
     *                     &lt;element name="geburtsname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                     &lt;element name="geburtsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                     &lt;element name="geburtsdatum.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/sequence>
     *                 &lt;attribute name="menge" type="{http://www.w3.org/2001/XMLSchema}long" default="50" />
     *                 &lt;attribute name="versatz" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geschaeftszeichen",
        "suche"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected String geschaeftszeichen;
        @XmlElement(required = true)
        protected NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten.Suche suche;

        /**
         * Gets the value of the geschaeftszeichen property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeschaeftszeichen() {
            return geschaeftszeichen;
        }

        /**
         * Sets the value of the geschaeftszeichen property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeschaeftszeichen(String value) {
            this.geschaeftszeichen = value;
        }

        /**
         * Gets the value of the suche property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten.Suche }
         *     
         */
        public NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten.Suche getSuche() {
            return suche;
        }

        /**
         * Sets the value of the suche property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten.Suche }
         *     
         */
        public void setSuche(NachrichtZvrSucheRegistrierungInput1000008 .Fachdaten.Suche value) {
            this.suche = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;sequence>
         *           &lt;element name="nachname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
         *           &lt;element name="nachname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *           &lt;element name="vorname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
         *           &lt;element name="vorname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *           &lt;element name="geburtsname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
         *           &lt;element name="geburtsname.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *           &lt;element name="geburtsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *           &lt;element name="geburtsdatum.fehlertolerant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;/sequence>
         *       &lt;/sequence>
         *       &lt;attribute name="menge" type="{http://www.w3.org/2001/XMLSchema}long" default="50" />
         *       &lt;attribute name="versatz" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nachname",
            "nachnameFehlertolerant",
            "vorname",
            "vornameFehlertolerant",
            "geburtsname",
            "geburtsnameFehlertolerant",
            "geburtsdatum",
            "geburtsdatumFehlertolerant"
        })
        public static class Suche {

            protected String nachname;
            @XmlElement(name = "nachname.fehlertolerant")
            protected Boolean nachnameFehlertolerant;
            protected String vorname;
            @XmlElement(name = "vorname.fehlertolerant")
            protected Boolean vornameFehlertolerant;
            protected String geburtsname;
            @XmlElement(name = "geburtsname.fehlertolerant")
            protected Boolean geburtsnameFehlertolerant;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar geburtsdatum;
            @XmlElement(name = "geburtsdatum.fehlertolerant")
            protected Boolean geburtsdatumFehlertolerant;
            @XmlAttribute(name = "menge")
            protected Long menge;
            @XmlAttribute(name = "versatz")
            protected Long versatz;

            /**
             * Gets the value of the nachname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNachname() {
                return nachname;
            }

            /**
             * Sets the value of the nachname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNachname(String value) {
                this.nachname = value;
            }

            /**
             * Gets the value of the nachnameFehlertolerant property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isNachnameFehlertolerant() {
                return nachnameFehlertolerant;
            }

            /**
             * Sets the value of the nachnameFehlertolerant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNachnameFehlertolerant(Boolean value) {
                this.nachnameFehlertolerant = value;
            }

            /**
             * Gets the value of the vorname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVorname() {
                return vorname;
            }

            /**
             * Sets the value of the vorname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVorname(String value) {
                this.vorname = value;
            }

            /**
             * Gets the value of the vornameFehlertolerant property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isVornameFehlertolerant() {
                return vornameFehlertolerant;
            }

            /**
             * Sets the value of the vornameFehlertolerant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setVornameFehlertolerant(Boolean value) {
                this.vornameFehlertolerant = value;
            }

            /**
             * Gets the value of the geburtsname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeburtsname() {
                return geburtsname;
            }

            /**
             * Sets the value of the geburtsname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeburtsname(String value) {
                this.geburtsname = value;
            }

            /**
             * Gets the value of the geburtsnameFehlertolerant property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGeburtsnameFehlertolerant() {
                return geburtsnameFehlertolerant;
            }

            /**
             * Sets the value of the geburtsnameFehlertolerant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGeburtsnameFehlertolerant(Boolean value) {
                this.geburtsnameFehlertolerant = value;
            }

            /**
             * Gets the value of the geburtsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGeburtsdatum() {
                return geburtsdatum;
            }

            /**
             * Sets the value of the geburtsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGeburtsdatum(XMLGregorianCalendar value) {
                this.geburtsdatum = value;
            }

            /**
             * Gets the value of the geburtsdatumFehlertolerant property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGeburtsdatumFehlertolerant() {
                return geburtsdatumFehlertolerant;
            }

            /**
             * Sets the value of the geburtsdatumFehlertolerant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGeburtsdatumFehlertolerant(Boolean value) {
                this.geburtsdatumFehlertolerant = value;
            }

            /**
             * Gets the value of the menge property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getMenge() {
                if (menge == null) {
                    return  50L;
                } else {
                    return menge;
                }
            }

            /**
             * Sets the value of the menge property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMenge(Long value) {
                this.menge = value;
            }

            /**
             * Gets the value of the versatz property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public long getVersatz() {
                if (versatz == null) {
                    return  0L;
                } else {
                    return versatz;
                }
            }

            /**
             * Sets the value of the versatz property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setVersatz(Long value) {
                this.versatz = value;
            }

        }

    }

}
