//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="aussonderungsobjekt" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte"/>
 *                             &lt;element name="fachdatenAussonderung" type="{http://www.xjustiz.de}Type.AUSS.Fachdaten" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.auss.anbieteverzeichnis.1300001")
public class NachrichtAussAnbieteverzeichnis1300001 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected NachrichtAussAnbieteverzeichnis1300001 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtAussAnbieteverzeichnis1300001 .Fachdaten }
     *     
     */
    public NachrichtAussAnbieteverzeichnis1300001 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtAussAnbieteverzeichnis1300001 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtAussAnbieteverzeichnis1300001 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="aussonderungsobjekt" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte"/>
     *                   &lt;element name="fachdatenAussonderung" type="{http://www.xjustiz.de}Type.AUSS.Fachdaten" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aussonderungsobjekt"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected List<NachrichtAussAnbieteverzeichnis1300001 .Fachdaten.Aussonderungsobjekt> aussonderungsobjekt;

        /**
         * Gets the value of the aussonderungsobjekt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aussonderungsobjekt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAussonderungsobjekt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NachrichtAussAnbieteverzeichnis1300001 .Fachdaten.Aussonderungsobjekt }
         * 
         * 
         */
        public List<NachrichtAussAnbieteverzeichnis1300001 .Fachdaten.Aussonderungsobjekt> getAussonderungsobjekt() {
            if (aussonderungsobjekt == null) {
                aussonderungsobjekt = new ArrayList<NachrichtAussAnbieteverzeichnis1300001 .Fachdaten.Aussonderungsobjekt>();
            }
            return this.aussonderungsobjekt;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte"/>
         *         &lt;element name="fachdatenAussonderung" type="{http://www.xjustiz.de}Type.AUSS.Fachdaten" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "schriftgutobjekte",
            "fachdatenAussonderung"
        })
        public static class Aussonderungsobjekt {

            @XmlElement(required = true)
            protected TypeGDSSchriftgutobjekte schriftgutobjekte;
            protected TypeAUSSFachdaten fachdatenAussonderung;

            /**
             * Gets the value of the schriftgutobjekte property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSSchriftgutobjekte }
             *     
             */
            public TypeGDSSchriftgutobjekte getSchriftgutobjekte() {
                return schriftgutobjekte;
            }

            /**
             * Sets the value of the schriftgutobjekte property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSSchriftgutobjekte }
             *     
             */
            public void setSchriftgutobjekte(TypeGDSSchriftgutobjekte value) {
                this.schriftgutobjekte = value;
            }

            /**
             * Gets the value of the fachdatenAussonderung property.
             * 
             * @return
             *     possible object is
             *     {@link TypeAUSSFachdaten }
             *     
             */
            public TypeAUSSFachdaten getFachdatenAussonderung() {
                return fachdatenAussonderung;
            }

            /**
             * Sets the value of the fachdatenAussonderung property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeAUSSFachdaten }
             *     
             */
            public void setFachdatenAussonderung(TypeAUSSFachdaten value) {
                this.fachdatenAussonderung = value;
            }

        }

    }

}
