//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="verfahrensdaten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                             &lt;element name="datum.einschlaegigkeitsmarkierung" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="einstellungsdatum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="antragsgegner" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
 *                             &lt;element name="antragssteller" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "schriftgutobjekte",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.zssr.mitteilungEinschlaegig.2300004")
public class NachrichtZssrMitteilungEinschlaegig2300004 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected TypeGDSSchriftgutobjekte schriftgutobjekte;
    @XmlElement(required = true)
    protected NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the schriftgutobjekte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public TypeGDSSchriftgutobjekte getSchriftgutobjekte() {
        return schriftgutobjekte;
    }

    /**
     * Sets the value of the schriftgutobjekte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public void setSchriftgutobjekte(TypeGDSSchriftgutobjekte value) {
        this.schriftgutobjekte = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten }
     *     
     */
    public NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="verfahrensdaten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *                   &lt;element name="datum.einschlaegigkeitsmarkierung" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="einstellungsdatum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="antragsgegner" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
     *                   &lt;element name="antragssteller" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "verfahrensdaten"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten.Verfahrensdaten verfahrensdaten;

        /**
         * Gets the value of the verfahrensdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten.Verfahrensdaten }
         *     
         */
        public NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten.Verfahrensdaten getVerfahrensdaten() {
            return verfahrensdaten;
        }

        /**
         * Sets the value of the verfahrensdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten.Verfahrensdaten }
         *     
         */
        public void setVerfahrensdaten(NachrichtZssrMitteilungEinschlaegig2300004 .Fachdaten.Verfahrensdaten value) {
            this.verfahrensdaten = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
         *         &lt;element name="datum.einschlaegigkeitsmarkierung" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="einstellungsdatum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="antragsgegner" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
         *         &lt;element name="antragssteller" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "registernummer",
            "datumEinschlaegigkeitsmarkierung",
            "einstellungsdatum",
            "antragsgegner",
            "antragssteller"
        })
        public static class Verfahrensdaten {

            @XmlElement(required = true)
            protected String registernummer;
            @XmlElement(name = "datum.einschlaegigkeitsmarkierung", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumEinschlaegigkeitsmarkierung;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar einstellungsdatum;
            @XmlElement(required = true)
            protected List<String> antragsgegner;
            @XmlElement(required = true)
            protected List<String> antragssteller;

            /**
             * Gets the value of the registernummer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegisternummer() {
                return registernummer;
            }

            /**
             * Sets the value of the registernummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegisternummer(String value) {
                this.registernummer = value;
            }

            /**
             * Gets the value of the datumEinschlaegigkeitsmarkierung property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumEinschlaegigkeitsmarkierung() {
                return datumEinschlaegigkeitsmarkierung;
            }

            /**
             * Sets the value of the datumEinschlaegigkeitsmarkierung property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumEinschlaegigkeitsmarkierung(XMLGregorianCalendar value) {
                this.datumEinschlaegigkeitsmarkierung = value;
            }

            /**
             * Gets the value of the einstellungsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEinstellungsdatum() {
                return einstellungsdatum;
            }

            /**
             * Sets the value of the einstellungsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEinstellungsdatum(XMLGregorianCalendar value) {
                this.einstellungsdatum = value;
            }

            /**
             * Gets the value of the antragsgegner property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the antragsgegner property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAntragsgegner().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAntragsgegner() {
                if (antragsgegner == null) {
                    antragsgegner = new ArrayList<String>();
                }
                return this.antragsgegner;
            }

            /**
             * Gets the value of the antragssteller property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the antragssteller property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAntragssteller().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAntragssteller() {
                if (antragssteller == null) {
                    antragssteller = new ArrayList<String>();
                }
                return this.antragssteller;
            }

        }

    }

}
