//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ref.instanzdaten" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                             &lt;element name="verfahrensgegenstand" type="{http://www.xjustiz.de}Code.FAM.Gegenstandsbezeichnung" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
 *                   &lt;element name="heiratsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="auswahl_heiratsort" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="heiratsort.standesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
 *                             &lt;element name="heiratsort.keinStandesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="heiratsregister" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
 *                   &lt;element name="familienart" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="familienart" type="{http://www.xjustiz.de}Code.FAM.Familienart" minOccurs="0"/>
 *                             &lt;element name="ehezeit" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="auswahl_zustelldatum" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="zustelldatum.scheidungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="zustelldatum.trennungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="trennungszeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                   &lt;element name="rechtswahl.scheidungsrecht" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" minOccurs="0"/>
 *                   &lt;element name="scheidungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="rechtskraft.entscheidung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fachdaten.fam.version" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" fixed="1.2" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.fam.allgemein.0200001")
public class NachrichtFamAllgemein0200001 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtFamAllgemein0200001 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtFamAllgemein0200001 .Fachdaten }
     *     
     */
    public NachrichtFamAllgemein0200001 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtFamAllgemein0200001 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtFamAllgemein0200001 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ref.instanzdaten" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *                   &lt;element name="verfahrensgegenstand" type="{http://www.xjustiz.de}Code.FAM.Gegenstandsbezeichnung" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA" minOccurs="0"/>
     *         &lt;element name="heiratsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="auswahl_heiratsort" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="heiratsort.standesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
     *                   &lt;element name="heiratsort.keinStandesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="heiratsregister" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
     *         &lt;element name="familienart" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="familienart" type="{http://www.xjustiz.de}Code.FAM.Familienart" minOccurs="0"/>
     *                   &lt;element name="ehezeit" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="auswahl_zustelldatum" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="zustelldatum.scheidungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="zustelldatum.trennungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="trennungszeitpunkt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *         &lt;element name="rechtswahl.scheidungsrecht" type="{http://www.xjustiz.de}Code.GDS.Staaten.Typ3" minOccurs="0"/>
     *         &lt;element name="scheidungsdatum" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="rechtskraft.entscheidung" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="fachdaten.fam.version" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" fixed="1.2" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refInstanzdaten",
        "familienname",
        "heiratsdatum",
        "auswahlHeiratsort",
        "heiratsregister",
        "familienart",
        "auswahlZustelldatum",
        "trennungszeitpunkt",
        "rechtswahlScheidungsrecht",
        "scheidungsdatum",
        "rechtskraftEntscheidung"
    })
    public static class Fachdaten {

        @XmlElement(name = "ref.instanzdaten")
        protected List<NachrichtFamAllgemein0200001 .Fachdaten.RefInstanzdaten> refInstanzdaten;
        protected String familienname;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar heiratsdatum;
        @XmlElement(name = "auswahl_heiratsort")
        protected NachrichtFamAllgemein0200001 .Fachdaten.AuswahlHeiratsort auswahlHeiratsort;
        protected String heiratsregister;
        protected NachrichtFamAllgemein0200001 .Fachdaten.Familienart familienart;
        @XmlElement(name = "auswahl_zustelldatum")
        protected NachrichtFamAllgemein0200001 .Fachdaten.AuswahlZustelldatum auswahlZustelldatum;
        protected String trennungszeitpunkt;
        @XmlElement(name = "rechtswahl.scheidungsrecht")
        protected CodeGDSStaatenTyp3 rechtswahlScheidungsrecht;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar scheidungsdatum;
        @XmlElement(name = "rechtskraft.entscheidung")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar rechtskraftEntscheidung;
        @XmlAttribute(name = "fachdaten.fam.version", required = true)
        protected String fachdatenFamVersion;

        /**
         * Gets the value of the refInstanzdaten property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the refInstanzdaten property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRefInstanzdaten().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NachrichtFamAllgemein0200001 .Fachdaten.RefInstanzdaten }
         * 
         * 
         */
        public List<NachrichtFamAllgemein0200001 .Fachdaten.RefInstanzdaten> getRefInstanzdaten() {
            if (refInstanzdaten == null) {
                refInstanzdaten = new ArrayList<NachrichtFamAllgemein0200001 .Fachdaten.RefInstanzdaten>();
            }
            return this.refInstanzdaten;
        }

        /**
         * Gets the value of the familienname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFamilienname() {
            return familienname;
        }

        /**
         * Sets the value of the familienname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFamilienname(String value) {
            this.familienname = value;
        }

        /**
         * Gets the value of the heiratsdatum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getHeiratsdatum() {
            return heiratsdatum;
        }

        /**
         * Sets the value of the heiratsdatum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setHeiratsdatum(XMLGregorianCalendar value) {
            this.heiratsdatum = value;
        }

        /**
         * Gets the value of the auswahlHeiratsort property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.AuswahlHeiratsort }
         *     
         */
        public NachrichtFamAllgemein0200001 .Fachdaten.AuswahlHeiratsort getAuswahlHeiratsort() {
            return auswahlHeiratsort;
        }

        /**
         * Sets the value of the auswahlHeiratsort property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.AuswahlHeiratsort }
         *     
         */
        public void setAuswahlHeiratsort(NachrichtFamAllgemein0200001 .Fachdaten.AuswahlHeiratsort value) {
            this.auswahlHeiratsort = value;
        }

        /**
         * Gets the value of the heiratsregister property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeiratsregister() {
            return heiratsregister;
        }

        /**
         * Sets the value of the heiratsregister property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeiratsregister(String value) {
            this.heiratsregister = value;
        }

        /**
         * Gets the value of the familienart property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.Familienart }
         *     
         */
        public NachrichtFamAllgemein0200001 .Fachdaten.Familienart getFamilienart() {
            return familienart;
        }

        /**
         * Sets the value of the familienart property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.Familienart }
         *     
         */
        public void setFamilienart(NachrichtFamAllgemein0200001 .Fachdaten.Familienart value) {
            this.familienart = value;
        }

        /**
         * Gets the value of the auswahlZustelldatum property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.AuswahlZustelldatum }
         *     
         */
        public NachrichtFamAllgemein0200001 .Fachdaten.AuswahlZustelldatum getAuswahlZustelldatum() {
            return auswahlZustelldatum;
        }

        /**
         * Sets the value of the auswahlZustelldatum property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtFamAllgemein0200001 .Fachdaten.AuswahlZustelldatum }
         *     
         */
        public void setAuswahlZustelldatum(NachrichtFamAllgemein0200001 .Fachdaten.AuswahlZustelldatum value) {
            this.auswahlZustelldatum = value;
        }

        /**
         * Gets the value of the trennungszeitpunkt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrennungszeitpunkt() {
            return trennungszeitpunkt;
        }

        /**
         * Sets the value of the trennungszeitpunkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrennungszeitpunkt(String value) {
            this.trennungszeitpunkt = value;
        }

        /**
         * Gets the value of the rechtswahlScheidungsrecht property.
         * 
         * @return
         *     possible object is
         *     {@link CodeGDSStaatenTyp3 }
         *     
         */
        public CodeGDSStaatenTyp3 getRechtswahlScheidungsrecht() {
            return rechtswahlScheidungsrecht;
        }

        /**
         * Sets the value of the rechtswahlScheidungsrecht property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeGDSStaatenTyp3 }
         *     
         */
        public void setRechtswahlScheidungsrecht(CodeGDSStaatenTyp3 value) {
            this.rechtswahlScheidungsrecht = value;
        }

        /**
         * Gets the value of the scheidungsdatum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getScheidungsdatum() {
            return scheidungsdatum;
        }

        /**
         * Sets the value of the scheidungsdatum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setScheidungsdatum(XMLGregorianCalendar value) {
            this.scheidungsdatum = value;
        }

        /**
         * Gets the value of the rechtskraftEntscheidung property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRechtskraftEntscheidung() {
            return rechtskraftEntscheidung;
        }

        /**
         * Sets the value of the rechtskraftEntscheidung property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRechtskraftEntscheidung(XMLGregorianCalendar value) {
            this.rechtskraftEntscheidung = value;
        }

        /**
         * Gets the value of the fachdatenFamVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFachdatenFamVersion() {
            if (fachdatenFamVersion == null) {
                return "1.2";
            } else {
                return fachdatenFamVersion;
            }
        }

        /**
         * Sets the value of the fachdatenFamVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFachdatenFamVersion(String value) {
            this.fachdatenFamVersion = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="heiratsort.standesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
         *         &lt;element name="heiratsort.keinStandesamt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeE" minOccurs="0"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "heiratsortStandesamt",
            "heiratsortKeinStandesamt"
        })
        public static class AuswahlHeiratsort {

            @XmlElement(name = "heiratsort.standesamt")
            protected String heiratsortStandesamt;
            @XmlElement(name = "heiratsort.keinStandesamt")
            protected String heiratsortKeinStandesamt;

            /**
             * Gets the value of the heiratsortStandesamt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeiratsortStandesamt() {
                return heiratsortStandesamt;
            }

            /**
             * Sets the value of the heiratsortStandesamt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeiratsortStandesamt(String value) {
                this.heiratsortStandesamt = value;
            }

            /**
             * Gets the value of the heiratsortKeinStandesamt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeiratsortKeinStandesamt() {
                return heiratsortKeinStandesamt;
            }

            /**
             * Sets the value of the heiratsortKeinStandesamt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeiratsortKeinStandesamt(String value) {
                this.heiratsortKeinStandesamt = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="zustelldatum.scheidungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="zustelldatum.trennungsantrag" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zustelldatumScheidungsantrag",
            "zustelldatumTrennungsantrag"
        })
        public static class AuswahlZustelldatum {

            @XmlElement(name = "zustelldatum.scheidungsantrag")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar zustelldatumScheidungsantrag;
            @XmlElement(name = "zustelldatum.trennungsantrag")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar zustelldatumTrennungsantrag;

            /**
             * Gets the value of the zustelldatumScheidungsantrag property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getZustelldatumScheidungsantrag() {
                return zustelldatumScheidungsantrag;
            }

            /**
             * Sets the value of the zustelldatumScheidungsantrag property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setZustelldatumScheidungsantrag(XMLGregorianCalendar value) {
                this.zustelldatumScheidungsantrag = value;
            }

            /**
             * Gets the value of the zustelldatumTrennungsantrag property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getZustelldatumTrennungsantrag() {
                return zustelldatumTrennungsantrag;
            }

            /**
             * Sets the value of the zustelldatumTrennungsantrag property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setZustelldatumTrennungsantrag(XMLGregorianCalendar value) {
                this.zustelldatumTrennungsantrag = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="familienart" type="{http://www.xjustiz.de}Code.FAM.Familienart" minOccurs="0"/>
         *         &lt;element name="ehezeit" type="{http://www.xjustiz.de}Type.GDS.Xdomea.ZeitraumType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "familienart",
            "ehezeit"
        })
        public static class Familienart {

            protected CodeFAMFamilienart familienart;
            protected TypeGDSXdomeaZeitraumType ehezeit;

            /**
             * Gets the value of the familienart property.
             * 
             * @return
             *     possible object is
             *     {@link CodeFAMFamilienart }
             *     
             */
            public CodeFAMFamilienart getFamilienart() {
                return familienart;
            }

            /**
             * Sets the value of the familienart property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeFAMFamilienart }
             *     
             */
            public void setFamilienart(CodeFAMFamilienart value) {
                this.familienart = value;
            }

            /**
             * Gets the value of the ehezeit property.
             * 
             * @return
             *     possible object is
             *     {@link TypeGDSXdomeaZeitraumType }
             *     
             */
            public TypeGDSXdomeaZeitraumType getEhezeit() {
                return ehezeit;
            }

            /**
             * Sets the value of the ehezeit property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeGDSXdomeaZeitraumType }
             *     
             */
            public void setEhezeit(TypeGDSXdomeaZeitraumType value) {
                this.ehezeit = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ref.instanznummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
         *         &lt;element name="verfahrensgegenstand" type="{http://www.xjustiz.de}Code.FAM.Gegenstandsbezeichnung" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "refInstanznummer",
            "verfahrensgegenstand"
        })
        public static class RefInstanzdaten {

            @XmlElement(name = "ref.instanznummer", required = true)
            protected String refInstanznummer;
            @XmlElement(required = true)
            protected List<CodeFAMGegenstandsbezeichnung> verfahrensgegenstand;

            /**
             * Gets the value of the refInstanznummer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefInstanznummer() {
                return refInstanznummer;
            }

            /**
             * Sets the value of the refInstanznummer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefInstanznummer(String value) {
                this.refInstanznummer = value;
            }

            /**
             * Gets the value of the verfahrensgegenstand property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the verfahrensgegenstand property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVerfahrensgegenstand().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CodeFAMGegenstandsbezeichnung }
             * 
             * 
             */
            public List<CodeFAMGegenstandsbezeichnung> getVerfahrensgegenstand() {
                if (verfahrensgegenstand == null) {
                    verfahrensgegenstand = new ArrayList<CodeFAMGegenstandsbezeichnung>();
                }
                return this.verfahrensgegenstand;
            }

        }

    }

}
