//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Rangvorbehalt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Rangvorbehalt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="auswahl_art">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="gleichrangsvorbehalt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                   &lt;element name="vorrangsvorbehalt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="betrag" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/>
 *         &lt;element name="inhalt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="belastungsart" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="mehrmaligAusnutzbar" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="betroffeneBuchungsstelle" type="{http://www.xjustiz.de}Type.DABAG.Ref.Buchungsstelle" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="betroffenerEigentuemer" type="{http://www.xjustiz.de}Type.DABAG.Ref.Eigentuemer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="zuAenderndesRecht" type="{http://www.xjustiz.de}Type.DABAG.Ref.Belastung" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Rangvorbehalt", propOrder = {
    "auswahlArt",
    "betrag",
    "inhalt",
    "belastungsart",
    "mehrmaligAusnutzbar",
    "betroffeneBuchungsstelle",
    "betroffenerEigentuemer",
    "zuAenderndesRecht"
})
public class TypeDABAGRangvorbehalt {

    @XmlElement(name = "auswahl_art", required = true)
    protected TypeDABAGRangvorbehalt.AuswahlArt auswahlArt;
    protected TypeGDSGeldbetrag betrag;
    protected String inhalt;
    @XmlElement(required = true)
    protected String belastungsart;
    protected boolean mehrmaligAusnutzbar;
    protected List<TypeDABAGRefBuchungsstelle> betroffeneBuchungsstelle;
    protected List<TypeDABAGRefEigentuemer> betroffenerEigentuemer;
    @XmlElement(required = true)
    protected List<TypeDABAGRefBelastung> zuAenderndesRecht;

    /**
     * Gets the value of the auswahlArt property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGRangvorbehalt.AuswahlArt }
     *     
     */
    public TypeDABAGRangvorbehalt.AuswahlArt getAuswahlArt() {
        return auswahlArt;
    }

    /**
     * Sets the value of the auswahlArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGRangvorbehalt.AuswahlArt }
     *     
     */
    public void setAuswahlArt(TypeDABAGRangvorbehalt.AuswahlArt value) {
        this.auswahlArt = value;
    }

    /**
     * Gets the value of the betrag property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGeldbetrag }
     *     
     */
    public TypeGDSGeldbetrag getBetrag() {
        return betrag;
    }

    /**
     * Sets the value of the betrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGeldbetrag }
     *     
     */
    public void setBetrag(TypeGDSGeldbetrag value) {
        this.betrag = value;
    }

    /**
     * Gets the value of the inhalt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInhalt() {
        return inhalt;
    }

    /**
     * Sets the value of the inhalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInhalt(String value) {
        this.inhalt = value;
    }

    /**
     * Gets the value of the belastungsart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelastungsart() {
        return belastungsart;
    }

    /**
     * Sets the value of the belastungsart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelastungsart(String value) {
        this.belastungsart = value;
    }

    /**
     * Gets the value of the mehrmaligAusnutzbar property.
     * 
     */
    public boolean isMehrmaligAusnutzbar() {
        return mehrmaligAusnutzbar;
    }

    /**
     * Sets the value of the mehrmaligAusnutzbar property.
     * 
     */
    public void setMehrmaligAusnutzbar(boolean value) {
        this.mehrmaligAusnutzbar = value;
    }

    /**
     * Gets the value of the betroffeneBuchungsstelle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the betroffeneBuchungsstelle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBetroffeneBuchungsstelle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGRefBuchungsstelle }
     * 
     * 
     */
    public List<TypeDABAGRefBuchungsstelle> getBetroffeneBuchungsstelle() {
        if (betroffeneBuchungsstelle == null) {
            betroffeneBuchungsstelle = new ArrayList<TypeDABAGRefBuchungsstelle>();
        }
        return this.betroffeneBuchungsstelle;
    }

    /**
     * Gets the value of the betroffenerEigentuemer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the betroffenerEigentuemer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBetroffenerEigentuemer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGRefEigentuemer }
     * 
     * 
     */
    public List<TypeDABAGRefEigentuemer> getBetroffenerEigentuemer() {
        if (betroffenerEigentuemer == null) {
            betroffenerEigentuemer = new ArrayList<TypeDABAGRefEigentuemer>();
        }
        return this.betroffenerEigentuemer;
    }

    /**
     * Gets the value of the zuAenderndesRecht property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zuAenderndesRecht property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZuAenderndesRecht().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGRefBelastung }
     * 
     * 
     */
    public List<TypeDABAGRefBelastung> getZuAenderndesRecht() {
        if (zuAenderndesRecht == null) {
            zuAenderndesRecht = new ArrayList<TypeDABAGRefBelastung>();
        }
        return this.zuAenderndesRecht;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="gleichrangsvorbehalt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *         &lt;element name="vorrangsvorbehalt" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gleichrangsvorbehalt",
        "vorrangsvorbehalt"
    })
    public static class AuswahlArt {

        protected String gleichrangsvorbehalt;
        protected String vorrangsvorbehalt;

        /**
         * Gets the value of the gleichrangsvorbehalt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGleichrangsvorbehalt() {
            return gleichrangsvorbehalt;
        }

        /**
         * Sets the value of the gleichrangsvorbehalt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGleichrangsvorbehalt(String value) {
            this.gleichrangsvorbehalt = value;
        }

        /**
         * Gets the value of the vorrangsvorbehalt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVorrangsvorbehalt() {
            return vorrangsvorbehalt;
        }

        /**
         * Sets the value of the vorrangsvorbehalt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVorrangsvorbehalt(String value) {
            this.vorrangsvorbehalt = value;
        }

    }

}
