//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Mit diesem Type können Informationen zu dem Hersteller des Softwareprodukts, mit dem die XJustiz-Dateien erzeugt wurden, die Bezeichnung des Programms und seine Versionsnummer mitgeschickt werden. Durch diese Information kann im Supportfall die Fehlersuche systematisiert werden.
 * 
 * <p>Java class for Type.GDS.Herstellerinformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.GDS.Herstellerinformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nameDesProdukts" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/>
 *         &lt;element name="herstellerDesProdukts" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/>
 *         &lt;element name="version" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.GDS.Herstellerinformation", propOrder = {
    "nameDesProdukts",
    "herstellerDesProdukts",
    "version"
})
public class TypeGDSHerstellerinformation {

    protected String nameDesProdukts;
    protected String herstellerDesProdukts;
    protected String version;

    /**
     * Gets the value of the nameDesProdukts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDesProdukts() {
        return nameDesProdukts;
    }

    /**
     * Sets the value of the nameDesProdukts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDesProdukts(String value) {
        this.nameDesProdukts = value;
    }

    /**
     * Gets the value of the herstellerDesProdukts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHerstellerDesProdukts() {
        return herstellerDesProdukts;
    }

    /**
     * Sets the value of the herstellerDesProdukts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHerstellerDesProdukts(String value) {
        this.herstellerDesProdukts = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
