//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Type.KASSE.Entscheidung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.KASSE.Entscheidung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entscheidungsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="entscheidungsdatum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="entscheidungsaktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/>
 *         &lt;element name="entscheidungswert" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ref.beteiligter" type="{http://www.xjustiz.de}Type.GDS.Ref.Beteiligtennummer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.KASSE.Entscheidung", propOrder = {
    "entscheidungsnummer",
    "entscheidungsdatum",
    "entscheidungsaktenzeichen",
    "entscheidungswert",
    "refBeteiligter"
})
public class TypeKASSEEntscheidung {

    @XmlElement(required = true)
    protected String entscheidungsnummer;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar entscheidungsdatum;
    protected TypeGDSAktenzeichen entscheidungsaktenzeichen;
    protected Double entscheidungswert;
    @XmlElement(name = "ref.beteiligter")
    protected TypeGDSRefBeteiligtennummer refBeteiligter;

    /**
     * Gets the value of the entscheidungsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntscheidungsnummer() {
        return entscheidungsnummer;
    }

    /**
     * Sets the value of the entscheidungsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntscheidungsnummer(String value) {
        this.entscheidungsnummer = value;
    }

    /**
     * Gets the value of the entscheidungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntscheidungsdatum() {
        return entscheidungsdatum;
    }

    /**
     * Sets the value of the entscheidungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntscheidungsdatum(XMLGregorianCalendar value) {
        this.entscheidungsdatum = value;
    }

    /**
     * Gets the value of the entscheidungsaktenzeichen property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public TypeGDSAktenzeichen getEntscheidungsaktenzeichen() {
        return entscheidungsaktenzeichen;
    }

    /**
     * Sets the value of the entscheidungsaktenzeichen property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public void setEntscheidungsaktenzeichen(TypeGDSAktenzeichen value) {
        this.entscheidungsaktenzeichen = value;
    }

    /**
     * Gets the value of the entscheidungswert property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEntscheidungswert() {
        return entscheidungswert;
    }

    /**
     * Sets the value of the entscheidungswert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEntscheidungswert(Double value) {
        this.entscheidungswert = value;
    }

    /**
     * Gets the value of the refBeteiligter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefBeteiligtennummer }
     *     
     */
    public TypeGDSRefBeteiligtennummer getRefBeteiligter() {
        return refBeteiligter;
    }

    /**
     * Sets the value of the refBeteiligter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefBeteiligtennummer }
     *     
     */
    public void setRefBeteiligter(TypeGDSRefBeteiligtennummer value) {
        this.refBeteiligter = value;
    }

}
