//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Beteiligter.Grundbuchdaten complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Beteiligter.Grundbuchdaten">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referenzierungBeteiligter" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/>
 *         &lt;element name="wohnort" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeB" minOccurs="0"/>
 *         &lt;element name="amtstitelNotar" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="amtstaetigkeitenId" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="zusatzP15IIGBV" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="eintragungsname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Beteiligter.Grundbuchdaten", propOrder = {
    "referenzierungBeteiligter",
    "wohnort",
    "amtstitelNotar",
    "amtstaetigkeitenId",
    "zusatzP15IIGBV",
    "eintragungsname"
})
public class TypeDABAGBeteiligterGrundbuchdaten {

    @XmlElement(required = true)
    protected TypeGDSRefRollennummer referenzierungBeteiligter;
    protected String wohnort;
    protected String amtstitelNotar;
    protected String amtstaetigkeitenId;
    protected String zusatzP15IIGBV;
    protected String eintragungsname;

    /**
     * Gets the value of the referenzierungBeteiligter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public TypeGDSRefRollennummer getReferenzierungBeteiligter() {
        return referenzierungBeteiligter;
    }

    /**
     * Sets the value of the referenzierungBeteiligter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public void setReferenzierungBeteiligter(TypeGDSRefRollennummer value) {
        this.referenzierungBeteiligter = value;
    }

    /**
     * Gets the value of the wohnort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWohnort() {
        return wohnort;
    }

    /**
     * Sets the value of the wohnort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWohnort(String value) {
        this.wohnort = value;
    }

    /**
     * Gets the value of the amtstitelNotar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtstitelNotar() {
        return amtstitelNotar;
    }

    /**
     * Sets the value of the amtstitelNotar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtstitelNotar(String value) {
        this.amtstitelNotar = value;
    }

    /**
     * Gets the value of the amtstaetigkeitenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtstaetigkeitenId() {
        return amtstaetigkeitenId;
    }

    /**
     * Sets the value of the amtstaetigkeitenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtstaetigkeitenId(String value) {
        this.amtstaetigkeitenId = value;
    }

    /**
     * Gets the value of the zusatzP15IIGBV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZusatzP15IIGBV() {
        return zusatzP15IIGBV;
    }

    /**
     * Sets the value of the zusatzP15IIGBV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZusatzP15IIGBV(String value) {
        this.zusatzP15IIGBV = value;
    }

    /**
     * Gets the value of the eintragungsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEintragungsname() {
        return eintragungsname;
    }

    /**
     * Sets the value of the eintragungsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEintragungsname(String value) {
        this.eintragungsname = value;
    }

}
