//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Der Typ ermöglicht die Auswahl zwischen Gerichten und sonstigen Behörden. Sofern eine sonstige Behörde bereits unter den Beteiligtendaten erfasst wurde, ist im Element "beteiligter" die Beteiligtennummer anzugeben.
 * 
 * <p>Java class for Type.GDS.Behoerde complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.GDS.Behoerde">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="gericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3"/>
 *         &lt;element name="sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeD"/>
 *         &lt;element name="beteiligter" type="{http://www.xjustiz.de}Type.GDS.Ref.Beteiligtennummer"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.GDS.Behoerde", propOrder = {
    "gericht",
    "sonstige",
    "beteiligter"
})
@XmlSeeAlso({
    com.java.xsd.jaxb.NachrichtStrafBzrAuszugJustizZuExtern0500004 .Fachdaten.Entscheidung.Entscheidungsbehoerde.class,
    com.java.xsd.jaxb.NachrichtStrafFahndung0500016 .Fachdaten.Fahndung.Ausschreibungsbehoerde.class,
    com.java.xsd.jaxb.NachrichtStrafFahndung0500016 .Fachdaten.Fahndung.SachbearbeitendeDienststelle.class,
    com.java.xsd.jaxb.NachrichtStrafStrafvollstreckungsverfahren0500008 .Fachdaten.Entscheidung.Entscheidungsbehoerde.class,
    com.java.xsd.jaxb.TypeSTRAFEntscheidung.Entscheidungsbehoerde.class,
    com.java.xsd.jaxb.TypeSTRAFTat.Einleitbehoerde.class
})
public class TypeGDSBehoerde {

    protected CodeGDSGerichteTyp3 gericht;
    protected String sonstige;
    protected TypeGDSRefBeteiligtennummer beteiligter;

    /**
     * Gets the value of the gericht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public CodeGDSGerichteTyp3 getGericht() {
        return gericht;
    }

    /**
     * Sets the value of the gericht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public void setGericht(CodeGDSGerichteTyp3 value) {
        this.gericht = value;
    }

    /**
     * Gets the value of the sonstige property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonstige() {
        return sonstige;
    }

    /**
     * Sets the value of the sonstige property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonstige(String value) {
        this.sonstige = value;
    }

    /**
     * Gets the value of the beteiligter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefBeteiligtennummer }
     *     
     */
    public TypeGDSRefBeteiligtennummer getBeteiligter() {
        return beteiligter;
    }

    /**
     * Sets the value of the beteiligter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefBeteiligtennummer }
     *     
     */
    public void setBeteiligter(TypeGDSRefBeteiligtennummer value) {
        this.beteiligter = value;
    }

}
