//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Eintragungsgrundlagentyp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Eintragungsgrundlagentyp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="codeliste" type="{http://www.xjustiz.de}Code.DABAG.Eintragungsgrundlagentyp"/>
 *         &lt;element name="nichtGelisteterWert" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Eintragungsgrundlagentyp", propOrder = {
    "codeliste",
    "nichtGelisteterWert"
})
public class TypeDABAGEintragungsgrundlagentyp {

    protected CodeDABAGEintragungsgrundlagentyp codeliste;
    protected String nichtGelisteterWert;

    /**
     * Gets the value of the codeliste property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDABAGEintragungsgrundlagentyp }
     *     
     */
    public CodeDABAGEintragungsgrundlagentyp getCodeliste() {
        return codeliste;
    }

    /**
     * Sets the value of the codeliste property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDABAGEintragungsgrundlagentyp }
     *     
     */
    public void setCodeliste(CodeDABAGEintragungsgrundlagentyp value) {
        this.codeliste = value;
    }

    /**
     * Gets the value of the nichtGelisteterWert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNichtGelisteterWert() {
        return nichtGelisteterWert;
    }

    /**
     * Sets the value of the nichtGelisteterWert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNichtGelisteterWert(String value) {
        this.nichtGelisteterWert = value;
    }

}
