//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.VAG.Kurzmitteilung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.VAG.Kurzmitteilung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anfrage.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="auskunft.ID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="ordnungskriterium" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.VAG.Kurzmitteilung", propOrder = {
    "anfrageID",
    "auskunftID",
    "ordnungskriterium"
})
@XmlSeeAlso({
    com.java.xsd.jaxb.NachrichtVagKurzmitteilungVersorgungstraegerZuGericht0250008 .Fachdaten.class
})
public class TypeVAGKurzmitteilung {

    @XmlElement(name = "anfrage.ID", required = true)
    protected String anfrageID;
    @XmlElement(name = "auskunft.ID")
    protected String auskunftID;
    @XmlElement(required = true)
    protected String ordnungskriterium;

    /**
     * Gets the value of the anfrageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnfrageID() {
        return anfrageID;
    }

    /**
     * Sets the value of the anfrageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnfrageID(String value) {
        this.anfrageID = value;
    }

    /**
     * Gets the value of the auskunftID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuskunftID() {
        return auskunftID;
    }

    /**
     * Sets the value of the auskunftID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuskunftID(String value) {
        this.auskunftID = value;
    }

    /**
     * Gets the value of the ordnungskriterium property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdnungskriterium() {
        return ordnungskriterium;
    }

    /**
     * Sets the value of the ordnungskriterium property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdnungskriterium(String value) {
        this.ordnungskriterium = value;
    }

}
