//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.STRAF.BFJ.Statistik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.STRAF.BFJ.Statistik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gewerbeart" type="{http://www.xjustiz.de}Code.STRAF.BFJ.GZR.Gewerbeart.Typ3"/>
 *         &lt;element name="gewerbeschluessel" type="{http://www.xjustiz.de}Code.STRAF.BFJ.GZR.Gewerbeschluessel.Typ3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.STRAF.BFJ.Statistik", propOrder = {
    "gewerbeart",
    "gewerbeschluessel"
})
public class TypeSTRAFBFJStatistik {

    @XmlElement(required = true)
    protected CodeSTRAFBFJGZRGewerbeartTyp3 gewerbeart;
    @XmlElement(required = true)
    protected CodeSTRAFBFJGZRGewerbeschluesselTyp3 gewerbeschluessel;

    /**
     * Gets the value of the gewerbeart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSTRAFBFJGZRGewerbeartTyp3 }
     *     
     */
    public CodeSTRAFBFJGZRGewerbeartTyp3 getGewerbeart() {
        return gewerbeart;
    }

    /**
     * Sets the value of the gewerbeart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSTRAFBFJGZRGewerbeartTyp3 }
     *     
     */
    public void setGewerbeart(CodeSTRAFBFJGZRGewerbeartTyp3 value) {
        this.gewerbeart = value;
    }

    /**
     * Gets the value of the gewerbeschluessel property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSTRAFBFJGZRGewerbeschluesselTyp3 }
     *     
     */
    public CodeSTRAFBFJGZRGewerbeschluesselTyp3 getGewerbeschluessel() {
        return gewerbeschluessel;
    }

    /**
     * Sets the value of the gewerbeschluessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSTRAFBFJGZRGewerbeschluesselTyp3 }
     *     
     */
    public void setGewerbeschluessel(CodeSTRAFBFJGZRGewerbeschluesselTyp3 value) {
        this.gewerbeschluessel = value;
    }

}
