//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Type.ZVR.VollmachtdatenBasis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.ZVR.VollmachtdatenBasis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="datum.eintragung" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datum.vollmacht" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="urkundenrollennummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="aktenzeichen" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.ZVR.VollmachtdatenBasis", propOrder = {
    "registernummer",
    "datumEintragung",
    "datumVollmacht",
    "urkundenrollennummer",
    "aktenzeichen"
})
@XmlSeeAlso({
    TypeZVRVollmachtdaten.class
})
public class TypeZVRVollmachtdatenBasis {

    @XmlElement(required = true)
    protected String registernummer;
    @XmlElement(name = "datum.eintragung", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumEintragung;
    @XmlElement(name = "datum.vollmacht", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumVollmacht;
    protected String urkundenrollennummer;
    protected TypeGDSAktenzeichen aktenzeichen;

    /**
     * Gets the value of the registernummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisternummer() {
        return registernummer;
    }

    /**
     * Sets the value of the registernummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisternummer(String value) {
        this.registernummer = value;
    }

    /**
     * Gets the value of the datumEintragung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumEintragung() {
        return datumEintragung;
    }

    /**
     * Sets the value of the datumEintragung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumEintragung(XMLGregorianCalendar value) {
        this.datumEintragung = value;
    }

    /**
     * Gets the value of the datumVollmacht property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumVollmacht() {
        return datumVollmacht;
    }

    /**
     * Sets the value of the datumVollmacht property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumVollmacht(XMLGregorianCalendar value) {
        this.datumVollmacht = value;
    }

    /**
     * Gets the value of the urkundenrollennummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrkundenrollennummer() {
        return urkundenrollennummer;
    }

    /**
     * Sets the value of the urkundenrollennummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrkundenrollennummer(String value) {
        this.urkundenrollennummer = value;
    }

    /**
     * Gets the value of the aktenzeichen property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public TypeGDSAktenzeichen getAktenzeichen() {
        return aktenzeichen;
    }

    /**
     * Sets the value of the aktenzeichen property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public void setAktenzeichen(TypeGDSAktenzeichen value) {
        this.aktenzeichen = value;
    }

}
