//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Type.DABAG.Zustellungsbevollmaechtigter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Zustellungsbevollmaechtigter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eingangsdatumVollmacht" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="aktenzeichen.zustellungsbevollmaechtigung" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/>
 *         &lt;element name="aktenzeichen.dokument" type="{http://www.xjustiz.de}Type.GDS.Aktenzeichen" minOccurs="0"/>
 *         &lt;element name="bemerkung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="dokument" type="{http://www.xjustiz.de}Type.GDS.Ref.SGO"/>
 *         &lt;element name="person" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer"/>
 *         &lt;element name="eintragungsbeteiligter" type="{http://www.xjustiz.de}Type.DABAG.Eintragungsbeteiligter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Zustellungsbevollmaechtigter", propOrder = {
    "eingangsdatumVollmacht",
    "aktenzeichenZustellungsbevollmaechtigung",
    "aktenzeichenDokument",
    "bemerkung",
    "dokument",
    "person",
    "eintragungsbeteiligter"
})
public class TypeDABAGZustellungsbevollmaechtigter {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar eingangsdatumVollmacht;
    @XmlElement(name = "aktenzeichen.zustellungsbevollmaechtigung")
    protected TypeGDSAktenzeichen aktenzeichenZustellungsbevollmaechtigung;
    @XmlElement(name = "aktenzeichen.dokument")
    protected TypeGDSAktenzeichen aktenzeichenDokument;
    protected String bemerkung;
    @XmlElement(required = true)
    protected TypeGDSRefSGO dokument;
    @XmlElement(required = true)
    protected TypeGDSRefRollennummer person;
    protected TypeDABAGEintragungsbeteiligter eintragungsbeteiligter;

    /**
     * Gets the value of the eingangsdatumVollmacht property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEingangsdatumVollmacht() {
        return eingangsdatumVollmacht;
    }

    /**
     * Sets the value of the eingangsdatumVollmacht property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEingangsdatumVollmacht(XMLGregorianCalendar value) {
        this.eingangsdatumVollmacht = value;
    }

    /**
     * Gets the value of the aktenzeichenZustellungsbevollmaechtigung property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public TypeGDSAktenzeichen getAktenzeichenZustellungsbevollmaechtigung() {
        return aktenzeichenZustellungsbevollmaechtigung;
    }

    /**
     * Sets the value of the aktenzeichenZustellungsbevollmaechtigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public void setAktenzeichenZustellungsbevollmaechtigung(TypeGDSAktenzeichen value) {
        this.aktenzeichenZustellungsbevollmaechtigung = value;
    }

    /**
     * Gets the value of the aktenzeichenDokument property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public TypeGDSAktenzeichen getAktenzeichenDokument() {
        return aktenzeichenDokument;
    }

    /**
     * Sets the value of the aktenzeichenDokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSAktenzeichen }
     *     
     */
    public void setAktenzeichenDokument(TypeGDSAktenzeichen value) {
        this.aktenzeichenDokument = value;
    }

    /**
     * Gets the value of the bemerkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBemerkung() {
        return bemerkung;
    }

    /**
     * Sets the value of the bemerkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBemerkung(String value) {
        this.bemerkung = value;
    }

    /**
     * Gets the value of the dokument property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefSGO }
     *     
     */
    public TypeGDSRefSGO getDokument() {
        return dokument;
    }

    /**
     * Sets the value of the dokument property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefSGO }
     *     
     */
    public void setDokument(TypeGDSRefSGO value) {
        this.dokument = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public TypeGDSRefRollennummer getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSRefRollennummer }
     *     
     */
    public void setPerson(TypeGDSRefRollennummer value) {
        this.person = value;
    }

    /**
     * Gets the value of the eintragungsbeteiligter property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGEintragungsbeteiligter }
     *     
     */
    public TypeDABAGEintragungsbeteiligter getEintragungsbeteiligter() {
        return eintragungsbeteiligter;
    }

    /**
     * Sets the value of the eintragungsbeteiligter property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGEintragungsbeteiligter }
     *     
     */
    public void setEintragungsbeteiligter(TypeDABAGEintragungsbeteiligter value) {
        this.eintragungsbeteiligter = value;
    }

}
