//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="eintragungsanordnung" type="{http://www.xjustiz.de}Type.VSTR.Eintragungsanordnung.Schuldnerverzeichnis.Portal"/>
 *                   &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/>
 *                   &lt;element name="ergebnisDerVerarbeitung">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/>
 *                             &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.vstr.schuldnerverzeichnis.verarbeitungsbestaetigung.portal.0900004")
public class NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten }
     *     
     */
    public NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="eintragungsanordnung" type="{http://www.xjustiz.de}Type.VSTR.Eintragungsanordnung.Schuldnerverzeichnis.Portal"/>
     *         &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/>
     *         &lt;element name="ergebnisDerVerarbeitung">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/>
     *                   &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eintragungsanordnung",
        "beteiligterZusatz",
        "ergebnisDerVerarbeitung"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected TypeVSTREintragungsanordnungSchuldnerverzeichnisPortal eintragungsanordnung;
        @XmlElement(name = "beteiligter.zusatz", required = true)
        protected TypeVSTRBeteiligterZusatz beteiligterZusatz;
        @XmlElement(required = true)
        protected NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten.ErgebnisDerVerarbeitung ergebnisDerVerarbeitung;

        /**
         * Gets the value of the eintragungsanordnung property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTREintragungsanordnungSchuldnerverzeichnisPortal }
         *     
         */
        public TypeVSTREintragungsanordnungSchuldnerverzeichnisPortal getEintragungsanordnung() {
            return eintragungsanordnung;
        }

        /**
         * Sets the value of the eintragungsanordnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTREintragungsanordnungSchuldnerverzeichnisPortal }
         *     
         */
        public void setEintragungsanordnung(TypeVSTREintragungsanordnungSchuldnerverzeichnisPortal value) {
            this.eintragungsanordnung = value;
        }

        /**
         * Gets the value of the beteiligterZusatz property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public TypeVSTRBeteiligterZusatz getBeteiligterZusatz() {
            return beteiligterZusatz;
        }

        /**
         * Sets the value of the beteiligterZusatz property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public void setBeteiligterZusatz(TypeVSTRBeteiligterZusatz value) {
            this.beteiligterZusatz = value;
        }

        /**
         * Gets the value of the ergebnisDerVerarbeitung property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten.ErgebnisDerVerarbeitung }
         *     
         */
        public NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten.ErgebnisDerVerarbeitung getErgebnisDerVerarbeitung() {
            return ergebnisDerVerarbeitung;
        }

        /**
         * Sets the value of the ergebnisDerVerarbeitung property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten.ErgebnisDerVerarbeitung }
         *     
         */
        public void setErgebnisDerVerarbeitung(NachrichtVstrSchuldnerverzeichnisVerarbeitungsbestaetigungPortal0900004 .Fachdaten.ErgebnisDerVerarbeitung value) {
            this.ergebnisDerVerarbeitung = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ergebnis.code" type="{http://www.xjustiz.de}Code.VSTR.Verarbeitungsergebnis.Schuldnerverzeichnis"/>
         *         &lt;element name="ergebnis.ergaenzenderFehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ergebnisCode",
            "ergebnisErgaenzenderFehlertext"
        })
        public static class ErgebnisDerVerarbeitung {

            @XmlElement(name = "ergebnis.code", required = true)
            protected CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis ergebnisCode;
            @XmlElement(name = "ergebnis.ergaenzenderFehlertext")
            protected String ergebnisErgaenzenderFehlertext;

            /**
             * Gets the value of the ergebnisCode property.
             * 
             * @return
             *     possible object is
             *     {@link CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis }
             *     
             */
            public CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis getErgebnisCode() {
                return ergebnisCode;
            }

            /**
             * Sets the value of the ergebnisCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis }
             *     
             */
            public void setErgebnisCode(CodeVSTRVerarbeitungsergebnisSchuldnerverzeichnis value) {
                this.ergebnisCode = value;
            }

            /**
             * Gets the value of the ergebnisErgaenzenderFehlertext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getErgebnisErgaenzenderFehlertext() {
                return ergebnisErgaenzenderFehlertext;
            }

            /**
             * Sets the value of the ergebnisErgaenzenderFehlertext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setErgebnisErgaenzenderFehlertext(String value) {
                this.ergebnisErgaenzenderFehlertext = value;
            }

        }

    }

}
