//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="schriftgutobjekte" type="{http://www.xjustiz.de}Type.GDS.Schriftgutobjekte" minOccurs="0"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="auswahl_GegenstandDerNachricht">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="ersuchenSachentscheidung" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ersuchenSachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.ErsuchenSachentscheidung"/>
 *                                       &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="sachentscheidung" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="sachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.Sachentscheidung"/>
 *                                       &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                                       &lt;element name="adressatDerSachentscheidung" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="datenDerUrkunde" type="{http://www.xjustiz.de}Type.GDS.Beurkundung" maxOccurs="unbounded"/>
 *                   &lt;element name="bundeslandfremdesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.BundeslandfremdesGrundbuchblatt" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="beschreibungDesBetroffenenRechts" type="{http://www.xjustiz.de}Type.ENOVA.BeschreibungDesBetroffenenRechts" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="artDesRechtsgeschaefts" type="{http://www.xjustiz.de}Type.ENOVA.ArtDesRechtsgeschaefts" minOccurs="0"/>
 *                   &lt;element name="gegenleistung" type="{http://www.xjustiz.de}Type.ENOVA.Gegenleistung" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="erwerber_veraeusserer" type="{http://www.xjustiz.de}Type.ENOVA.Erwerber_Veraeusserer" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="tagUebergabe_Anteilsuebergang" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "schriftgutobjekte",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.enova.entscheidung.2900003")
public class NachrichtEnovaEntscheidung2900003 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    protected TypeGDSSchriftgutobjekte schriftgutobjekte;
    @XmlElement(required = true)
    protected NachrichtEnovaEntscheidung2900003 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the schriftgutobjekte property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public TypeGDSSchriftgutobjekte getSchriftgutobjekte() {
        return schriftgutobjekte;
    }

    /**
     * Sets the value of the schriftgutobjekte property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSSchriftgutobjekte }
     *     
     */
    public void setSchriftgutobjekte(TypeGDSSchriftgutobjekte value) {
        this.schriftgutobjekte = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtEnovaEntscheidung2900003 .Fachdaten }
     *     
     */
    public NachrichtEnovaEntscheidung2900003 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtEnovaEntscheidung2900003 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtEnovaEntscheidung2900003 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="auswahl_GegenstandDerNachricht">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="ersuchenSachentscheidung" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ersuchenSachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.ErsuchenSachentscheidung"/>
     *                             &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="sachentscheidung" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="sachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.Sachentscheidung"/>
     *                             &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *                             &lt;element name="adressatDerSachentscheidung" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="datenDerUrkunde" type="{http://www.xjustiz.de}Type.GDS.Beurkundung" maxOccurs="unbounded"/>
     *         &lt;element name="bundeslandfremdesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.BundeslandfremdesGrundbuchblatt" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="beschreibungDesBetroffenenRechts" type="{http://www.xjustiz.de}Type.ENOVA.BeschreibungDesBetroffenenRechts" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="artDesRechtsgeschaefts" type="{http://www.xjustiz.de}Type.ENOVA.ArtDesRechtsgeschaefts" minOccurs="0"/>
     *         &lt;element name="gegenleistung" type="{http://www.xjustiz.de}Type.ENOVA.Gegenleistung" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="erwerber_veraeusserer" type="{http://www.xjustiz.de}Type.ENOVA.Erwerber_Veraeusserer" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="tagUebergabe_Anteilsuebergang" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auswahlGegenstandDerNachricht",
        "datenDerUrkunde",
        "bundeslandfremdesGrundbuchblatt",
        "beschreibungDesBetroffenenRechts",
        "artDesRechtsgeschaefts",
        "gegenleistung",
        "erwerberVeraeusserer",
        "tagUebergabeAnteilsuebergang"
    })
    public static class Fachdaten {

        @XmlElement(name = "auswahl_GegenstandDerNachricht", required = true)
        protected NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht auswahlGegenstandDerNachricht;
        @XmlElement(required = true)
        protected List<TypeGDSBeurkundung> datenDerUrkunde;
        protected List<TypeDABAGBundeslandfremdesGrundbuchblatt> bundeslandfremdesGrundbuchblatt;
        protected List<TypeENOVABeschreibungDesBetroffenenRechts> beschreibungDesBetroffenenRechts;
        protected TypeENOVAArtDesRechtsgeschaefts artDesRechtsgeschaefts;
        protected List<TypeENOVAGegenleistung> gegenleistung;
        @XmlElement(name = "erwerber_veraeusserer")
        protected List<TypeENOVAErwerberVeraeusserer> erwerberVeraeusserer;
        @XmlElement(name = "tagUebergabe_Anteilsuebergang")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar tagUebergabeAnteilsuebergang;

        /**
         * Gets the value of the auswahlGegenstandDerNachricht property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht }
         *     
         */
        public NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht getAuswahlGegenstandDerNachricht() {
            return auswahlGegenstandDerNachricht;
        }

        /**
         * Sets the value of the auswahlGegenstandDerNachricht property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht }
         *     
         */
        public void setAuswahlGegenstandDerNachricht(NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht value) {
            this.auswahlGegenstandDerNachricht = value;
        }

        /**
         * Gets the value of the datenDerUrkunde property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datenDerUrkunde property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatenDerUrkunde().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeGDSBeurkundung }
         * 
         * 
         */
        public List<TypeGDSBeurkundung> getDatenDerUrkunde() {
            if (datenDerUrkunde == null) {
                datenDerUrkunde = new ArrayList<TypeGDSBeurkundung>();
            }
            return this.datenDerUrkunde;
        }

        /**
         * Gets the value of the bundeslandfremdesGrundbuchblatt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bundeslandfremdesGrundbuchblatt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBundeslandfremdesGrundbuchblatt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeDABAGBundeslandfremdesGrundbuchblatt }
         * 
         * 
         */
        public List<TypeDABAGBundeslandfremdesGrundbuchblatt> getBundeslandfremdesGrundbuchblatt() {
            if (bundeslandfremdesGrundbuchblatt == null) {
                bundeslandfremdesGrundbuchblatt = new ArrayList<TypeDABAGBundeslandfremdesGrundbuchblatt>();
            }
            return this.bundeslandfremdesGrundbuchblatt;
        }

        /**
         * Gets the value of the beschreibungDesBetroffenenRechts property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the beschreibungDesBetroffenenRechts property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBeschreibungDesBetroffenenRechts().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVABeschreibungDesBetroffenenRechts }
         * 
         * 
         */
        public List<TypeENOVABeschreibungDesBetroffenenRechts> getBeschreibungDesBetroffenenRechts() {
            if (beschreibungDesBetroffenenRechts == null) {
                beschreibungDesBetroffenenRechts = new ArrayList<TypeENOVABeschreibungDesBetroffenenRechts>();
            }
            return this.beschreibungDesBetroffenenRechts;
        }

        /**
         * Gets the value of the artDesRechtsgeschaefts property.
         * 
         * @return
         *     possible object is
         *     {@link TypeENOVAArtDesRechtsgeschaefts }
         *     
         */
        public TypeENOVAArtDesRechtsgeschaefts getArtDesRechtsgeschaefts() {
            return artDesRechtsgeschaefts;
        }

        /**
         * Sets the value of the artDesRechtsgeschaefts property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeENOVAArtDesRechtsgeschaefts }
         *     
         */
        public void setArtDesRechtsgeschaefts(TypeENOVAArtDesRechtsgeschaefts value) {
            this.artDesRechtsgeschaefts = value;
        }

        /**
         * Gets the value of the gegenleistung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gegenleistung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGegenleistung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVAGegenleistung }
         * 
         * 
         */
        public List<TypeENOVAGegenleistung> getGegenleistung() {
            if (gegenleistung == null) {
                gegenleistung = new ArrayList<TypeENOVAGegenleistung>();
            }
            return this.gegenleistung;
        }

        /**
         * Gets the value of the erwerberVeraeusserer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the erwerberVeraeusserer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getErwerberVeraeusserer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeENOVAErwerberVeraeusserer }
         * 
         * 
         */
        public List<TypeENOVAErwerberVeraeusserer> getErwerberVeraeusserer() {
            if (erwerberVeraeusserer == null) {
                erwerberVeraeusserer = new ArrayList<TypeENOVAErwerberVeraeusserer>();
            }
            return this.erwerberVeraeusserer;
        }

        /**
         * Gets the value of the tagUebergabeAnteilsuebergang property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTagUebergabeAnteilsuebergang() {
            return tagUebergabeAnteilsuebergang;
        }

        /**
         * Sets the value of the tagUebergabeAnteilsuebergang property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTagUebergabeAnteilsuebergang(XMLGregorianCalendar value) {
            this.tagUebergabeAnteilsuebergang = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="ersuchenSachentscheidung" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ersuchenSachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.ErsuchenSachentscheidung"/>
         *                   &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="sachentscheidung" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="sachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.Sachentscheidung"/>
         *                   &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
         *                   &lt;element name="adressatDerSachentscheidung" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ersuchenSachentscheidung",
            "sachentscheidung"
        })
        public static class AuswahlGegenstandDerNachricht {

            protected List<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.ErsuchenSachentscheidung> ersuchenSachentscheidung;
            protected List<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.Sachentscheidung> sachentscheidung;

            /**
             * Gets the value of the ersuchenSachentscheidung property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ersuchenSachentscheidung property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getErsuchenSachentscheidung().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.ErsuchenSachentscheidung }
             * 
             * 
             */
            public List<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.ErsuchenSachentscheidung> getErsuchenSachentscheidung() {
                if (ersuchenSachentscheidung == null) {
                    ersuchenSachentscheidung = new ArrayList<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.ErsuchenSachentscheidung>();
                }
                return this.ersuchenSachentscheidung;
            }

            /**
             * Gets the value of the sachentscheidung property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sachentscheidung property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSachentscheidung().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.Sachentscheidung }
             * 
             * 
             */
            public List<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.Sachentscheidung> getSachentscheidung() {
                if (sachentscheidung == null) {
                    sachentscheidung = new ArrayList<NachrichtEnovaEntscheidung2900003 .Fachdaten.AuswahlGegenstandDerNachricht.Sachentscheidung>();
                }
                return this.sachentscheidung;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ersuchenSachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.ErsuchenSachentscheidung"/>
             *         &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ersuchenSachentscheidung",
                "hinweiseSonstige"
            })
            public static class ErsuchenSachentscheidung {

                @XmlElement(required = true)
                protected CodeENOVAErsuchenSachentscheidung ersuchenSachentscheidung;
                @XmlElement(name = "hinweise_sonstige")
                protected String hinweiseSonstige;

                /**
                 * Gets the value of the ersuchenSachentscheidung property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CodeENOVAErsuchenSachentscheidung }
                 *     
                 */
                public CodeENOVAErsuchenSachentscheidung getErsuchenSachentscheidung() {
                    return ersuchenSachentscheidung;
                }

                /**
                 * Sets the value of the ersuchenSachentscheidung property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CodeENOVAErsuchenSachentscheidung }
                 *     
                 */
                public void setErsuchenSachentscheidung(CodeENOVAErsuchenSachentscheidung value) {
                    this.ersuchenSachentscheidung = value;
                }

                /**
                 * Gets the value of the hinweiseSonstige property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHinweiseSonstige() {
                    return hinweiseSonstige;
                }

                /**
                 * Sets the value of the hinweiseSonstige property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHinweiseSonstige(String value) {
                    this.hinweiseSonstige = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="sachentscheidung" type="{http://www.xjustiz.de}Code.ENOVA.Sachentscheidung"/>
             *         &lt;element name="hinweise_sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
             *         &lt;element name="adressatDerSachentscheidung" type="{http://www.xjustiz.de}Type.GDS.Ref.Rollennummer" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sachentscheidung",
                "hinweiseSonstige",
                "adressatDerSachentscheidung"
            })
            public static class Sachentscheidung {

                @XmlElement(required = true)
                protected CodeENOVASachentscheidung sachentscheidung;
                @XmlElement(name = "hinweise_sonstige")
                protected String hinweiseSonstige;
                protected List<TypeGDSRefRollennummer> adressatDerSachentscheidung;

                /**
                 * Gets the value of the sachentscheidung property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CodeENOVASachentscheidung }
                 *     
                 */
                public CodeENOVASachentscheidung getSachentscheidung() {
                    return sachentscheidung;
                }

                /**
                 * Sets the value of the sachentscheidung property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CodeENOVASachentscheidung }
                 *     
                 */
                public void setSachentscheidung(CodeENOVASachentscheidung value) {
                    this.sachentscheidung = value;
                }

                /**
                 * Gets the value of the hinweiseSonstige property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHinweiseSonstige() {
                    return hinweiseSonstige;
                }

                /**
                 * Sets the value of the hinweiseSonstige property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHinweiseSonstige(String value) {
                    this.hinweiseSonstige = value;
                }

                /**
                 * Gets the value of the adressatDerSachentscheidung property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the adressatDerSachentscheidung property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAdressatDerSachentscheidung().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TypeGDSRefRollennummer }
                 * 
                 * 
                 */
                public List<TypeGDSRefRollennummer> getAdressatDerSachentscheidung() {
                    if (adressatDerSachentscheidung == null) {
                        adressatDerSachentscheidung = new ArrayList<TypeGDSRefRollennummer>();
                    }
                    return this.adressatDerSachentscheidung;
                }

            }

        }

    }

}
