//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="eintragungsanordnung" type="{http://www.xjustiz.de}Type.VSTR.Eintragungsanordnung.Schuldnerverzeichnis"/>
 *                   &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.vstr.schuldnerverzeichnis.eintragung.korrektur.0900003")
public class NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 .Fachdaten }
     *     
     */
    public NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtVstrSchuldnerverzeichnisEintragungKorrektur0900003 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="eintragungsanordnung" type="{http://www.xjustiz.de}Type.VSTR.Eintragungsanordnung.Schuldnerverzeichnis"/>
     *         &lt;element name="beteiligter.zusatz" type="{http://www.xjustiz.de}Type.VSTR.Beteiligter.Zusatz"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eintragungsanordnung",
        "beteiligterZusatz"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected TypeVSTREintragungsanordnungSchuldnerverzeichnis eintragungsanordnung;
        @XmlElement(name = "beteiligter.zusatz", required = true)
        protected TypeVSTRBeteiligterZusatz beteiligterZusatz;

        /**
         * Gets the value of the eintragungsanordnung property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTREintragungsanordnungSchuldnerverzeichnis }
         *     
         */
        public TypeVSTREintragungsanordnungSchuldnerverzeichnis getEintragungsanordnung() {
            return eintragungsanordnung;
        }

        /**
         * Sets the value of the eintragungsanordnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTREintragungsanordnungSchuldnerverzeichnis }
         *     
         */
        public void setEintragungsanordnung(TypeVSTREintragungsanordnungSchuldnerverzeichnis value) {
            this.eintragungsanordnung = value;
        }

        /**
         * Gets the value of the beteiligterZusatz property.
         * 
         * @return
         *     possible object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public TypeVSTRBeteiligterZusatz getBeteiligterZusatz() {
            return beteiligterZusatz;
        }

        /**
         * Sets the value of the beteiligterZusatz property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeVSTRBeteiligterZusatz }
         *     
         */
        public void setBeteiligterZusatz(TypeVSTRBeteiligterZusatz value) {
            this.beteiligterZusatz = value;
        }

    }

}
