//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="steuerungsdaten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Auskunft.Typ3"/>
 *                             &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="entscheidungsdaten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="anzahlEntscheidungen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                             &lt;element name="entscheidung" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/>
 *                                       &lt;element name="inhaltDerEntscheidung">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/>
 *                                                 &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/>
 *                                                 &lt;element name="ausgangszusatztext" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ausgangszusatztext" maxOccurs="unbounded" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.straf.bfj.gzr.auskunftserteilung.auskunft.0500402")
public class NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten }
     *     
     */
    public NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="steuerungsdaten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Auskunft.Typ3"/>
     *                   &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="weitereAngabenBeteiligter" type="{http://www.xjustiz.de}Type.STRAF.BFJ.WeitereAngabenBeteiligter" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="entscheidungsdaten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="anzahlEntscheidungen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *                   &lt;element name="entscheidung" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/>
     *                             &lt;element name="inhaltDerEntscheidung">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/>
     *                                       &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/>
     *                                       &lt;element name="ausgangszusatztext" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ausgangszusatztext" maxOccurs="unbounded" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "steuerungsdaten",
        "weitereAngabenBeteiligter",
        "entscheidungsdaten"
    })
    public static class Fachdaten {

        @XmlElement(required = true)
        protected NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Steuerungsdaten steuerungsdaten;
        protected List<TypeSTRAFBFJWeitereAngabenBeteiligter> weitereAngabenBeteiligter;
        @XmlElement(required = true)
        protected NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten entscheidungsdaten;

        /**
         * Gets the value of the steuerungsdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Steuerungsdaten }
         *     
         */
        public NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Steuerungsdaten getSteuerungsdaten() {
            return steuerungsdaten;
        }

        /**
         * Sets the value of the steuerungsdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Steuerungsdaten }
         *     
         */
        public void setSteuerungsdaten(NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Steuerungsdaten value) {
            this.steuerungsdaten = value;
        }

        /**
         * Gets the value of the weitereAngabenBeteiligter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the weitereAngabenBeteiligter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWeitereAngabenBeteiligter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TypeSTRAFBFJWeitereAngabenBeteiligter }
         * 
         * 
         */
        public List<TypeSTRAFBFJWeitereAngabenBeteiligter> getWeitereAngabenBeteiligter() {
            if (weitereAngabenBeteiligter == null) {
                weitereAngabenBeteiligter = new ArrayList<TypeSTRAFBFJWeitereAngabenBeteiligter>();
            }
            return this.weitereAngabenBeteiligter;
        }

        /**
         * Gets the value of the entscheidungsdaten property.
         * 
         * @return
         *     possible object is
         *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten }
         *     
         */
        public NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten getEntscheidungsdaten() {
            return entscheidungsdaten;
        }

        /**
         * Sets the value of the entscheidungsdaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten }
         *     
         */
        public void setEntscheidungsdaten(NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten value) {
            this.entscheidungsdaten = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="anzahlEntscheidungen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
         *         &lt;element name="entscheidung" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/>
         *                   &lt;element name="inhaltDerEntscheidung">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/>
         *                             &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/>
         *                             &lt;element name="ausgangszusatztext" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ausgangszusatztext" maxOccurs="unbounded" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "anzahlEntscheidungen",
            "entscheidung"
        })
        public static class Entscheidungsdaten {

            @XmlElement(required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger anzahlEntscheidungen;
            protected List<NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung> entscheidung;

            /**
             * Gets the value of the anzahlEntscheidungen property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAnzahlEntscheidungen() {
                return anzahlEntscheidungen;
            }

            /**
             * Sets the value of the anzahlEntscheidungen property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAnzahlEntscheidungen(BigInteger value) {
                this.anzahlEntscheidungen = value;
            }

            /**
             * Gets the value of the entscheidung property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the entscheidung property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEntscheidung().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung }
             * 
             * 
             */
            public List<NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung> getEntscheidung() {
                if (entscheidung == null) {
                    entscheidung = new ArrayList<NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung>();
                }
                return this.entscheidung;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ordnungsdaten" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ordnungsdaten"/>
             *         &lt;element name="inhaltDerEntscheidung">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/>
             *                   &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/>
             *                   &lt;element name="ausgangszusatztext" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ausgangszusatztext" maxOccurs="unbounded" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ordnungsdaten",
                "inhaltDerEntscheidung"
            })
            public static class Entscheidung {

                @XmlElement(required = true)
                protected TypeSTRAFBFJOrdnungsdaten ordnungsdaten;
                @XmlElement(required = true)
                protected NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung.InhaltDerEntscheidung inhaltDerEntscheidung;

                /**
                 * Gets the value of the ordnungsdaten property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TypeSTRAFBFJOrdnungsdaten }
                 *     
                 */
                public TypeSTRAFBFJOrdnungsdaten getOrdnungsdaten() {
                    return ordnungsdaten;
                }

                /**
                 * Sets the value of the ordnungsdaten property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TypeSTRAFBFJOrdnungsdaten }
                 *     
                 */
                public void setOrdnungsdaten(TypeSTRAFBFJOrdnungsdaten value) {
                    this.ordnungsdaten = value;
                }

                /**
                 * Gets the value of the inhaltDerEntscheidung property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung.InhaltDerEntscheidung }
                 *     
                 */
                public NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung.InhaltDerEntscheidung getInhaltDerEntscheidung() {
                    return inhaltDerEntscheidung;
                }

                /**
                 * Sets the value of the inhaltDerEntscheidung property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung.InhaltDerEntscheidung }
                 *     
                 */
                public void setInhaltDerEntscheidung(NachrichtStrafBfjGzrAuskunftserteilungAuskunft0500402 .Fachdaten.Entscheidungsdaten.Entscheidung.InhaltDerEntscheidung value) {
                    this.inhaltDerEntscheidung = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="datenRechtswirksamkeit" type="{http://www.xjustiz.de}Type.STRAF.BFJ.DatenRechtswirksamkeit" minOccurs="0"/>
                 *         &lt;element name="geldbusse" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Betrag" minOccurs="0"/>
                 *         &lt;element name="ausgangszusatztext" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Ausgangszusatztext" maxOccurs="unbounded" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "datenRechtswirksamkeit",
                    "geldbusse",
                    "ausgangszusatztext"
                })
                public static class InhaltDerEntscheidung {

                    protected TypeSTRAFBFJDatenRechtswirksamkeit datenRechtswirksamkeit;
                    protected TypeSTRAFBFJBetrag geldbusse;
                    protected List<TypeSTRAFBFJAusgangszusatztext> ausgangszusatztext;

                    /**
                     * Gets the value of the datenRechtswirksamkeit property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TypeSTRAFBFJDatenRechtswirksamkeit }
                     *     
                     */
                    public TypeSTRAFBFJDatenRechtswirksamkeit getDatenRechtswirksamkeit() {
                        return datenRechtswirksamkeit;
                    }

                    /**
                     * Sets the value of the datenRechtswirksamkeit property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TypeSTRAFBFJDatenRechtswirksamkeit }
                     *     
                     */
                    public void setDatenRechtswirksamkeit(TypeSTRAFBFJDatenRechtswirksamkeit value) {
                        this.datenRechtswirksamkeit = value;
                    }

                    /**
                     * Gets the value of the geldbusse property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TypeSTRAFBFJBetrag }
                     *     
                     */
                    public TypeSTRAFBFJBetrag getGeldbusse() {
                        return geldbusse;
                    }

                    /**
                     * Sets the value of the geldbusse property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TypeSTRAFBFJBetrag }
                     *     
                     */
                    public void setGeldbusse(TypeSTRAFBFJBetrag value) {
                        this.geldbusse = value;
                    }

                    /**
                     * Gets the value of the ausgangszusatztext property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the ausgangszusatztext property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getAusgangszusatztext().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link TypeSTRAFBFJAusgangszusatztext }
                     * 
                     * 
                     */
                    public List<TypeSTRAFBFJAusgangszusatztext> getAusgangszusatztext() {
                        if (ausgangszusatztext == null) {
                            ausgangszusatztext = new ArrayList<TypeSTRAFBFJAusgangszusatztext>();
                        }
                        return this.ausgangszusatztext;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nachrichtencode" type="{http://www.xjustiz.de}Code.STRAF.BFJ.Nachrichtencode.GZR.Auskunft.Typ3"/>
         *         &lt;element name="verwendungszweck" type="{http://www.xjustiz.de}Type.STRAF.BFJ.Verwendungszweck"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nachrichtencode",
            "verwendungszweck"
        })
        public static class Steuerungsdaten {

            @XmlElement(required = true)
            protected CodeSTRAFBFJNachrichtencodeGZRAuskunftTyp3 nachrichtencode;
            @XmlElement(required = true)
            protected TypeSTRAFBFJVerwendungszweck verwendungszweck;

            /**
             * Gets the value of the nachrichtencode property.
             * 
             * @return
             *     possible object is
             *     {@link CodeSTRAFBFJNachrichtencodeGZRAuskunftTyp3 }
             *     
             */
            public CodeSTRAFBFJNachrichtencodeGZRAuskunftTyp3 getNachrichtencode() {
                return nachrichtencode;
            }

            /**
             * Sets the value of the nachrichtencode property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeSTRAFBFJNachrichtencodeGZRAuskunftTyp3 }
             *     
             */
            public void setNachrichtencode(CodeSTRAFBFJNachrichtencodeGZRAuskunftTyp3 value) {
                this.nachrichtencode = value;
            }

            /**
             * Gets the value of the verwendungszweck property.
             * 
             * @return
             *     possible object is
             *     {@link TypeSTRAFBFJVerwendungszweck }
             *     
             */
            public TypeSTRAFBFJVerwendungszweck getVerwendungszweck() {
                return verwendungszweck;
            }

            /**
             * Sets the value of the verwendungszweck property.
             * 
             * @param value
             *     allowed object is
             *     {@link TypeSTRAFBFJVerwendungszweck }
             *     
             */
            public void setVerwendungszweck(TypeSTRAFBFJVerwendungszweck value) {
                this.verwendungszweck = value;
            }

        }

    }

}
