//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nachrichtenkopf" type="{http://www.xjustiz.de}Type.GDS.Nachrichtenkopf"/>
 *         &lt;element name="grunddaten" type="{http://www.xjustiz.de}Type.GDS.Grunddaten"/>
 *         &lt;element name="fachdaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nachrichtID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                   &lt;element name="antwortID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                   &lt;element name="fehlercode" type="{http://www.xjustiz.de}Code.ZPO.Fehlercode"/>
 *                   &lt;element name="fehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                   &lt;element name="anfrage.parameter" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nachrichtenkopf",
    "grunddaten",
    "fachdaten"
})
@XmlRootElement(name = "nachricht.zpo.fehlermeldung.1500005")
public class NachrichtZpoFehlermeldung1500005 {

    @XmlElement(required = true)
    protected TypeGDSNachrichtenkopf nachrichtenkopf;
    @XmlElement(required = true)
    protected TypeGDSGrunddaten grunddaten;
    @XmlElement(required = true)
    protected NachrichtZpoFehlermeldung1500005 .Fachdaten fachdaten;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public TypeGDSNachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSNachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(TypeGDSNachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the grunddaten property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public TypeGDSGrunddaten getGrunddaten() {
        return grunddaten;
    }

    /**
     * Sets the value of the grunddaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGrunddaten }
     *     
     */
    public void setGrunddaten(TypeGDSGrunddaten value) {
        this.grunddaten = value;
    }

    /**
     * Gets the value of the fachdaten property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtZpoFehlermeldung1500005 .Fachdaten }
     *     
     */
    public NachrichtZpoFehlermeldung1500005 .Fachdaten getFachdaten() {
        return fachdaten;
    }

    /**
     * Sets the value of the fachdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtZpoFehlermeldung1500005 .Fachdaten }
     *     
     */
    public void setFachdaten(NachrichtZpoFehlermeldung1500005 .Fachdaten value) {
        this.fachdaten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nachrichtID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *         &lt;element name="antwortID" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *         &lt;element name="fehlercode" type="{http://www.xjustiz.de}Code.ZPO.Fehlercode"/>
     *         &lt;element name="fehlertext" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *         &lt;element name="anfrage.parameter" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nachrichtID",
        "antwortID",
        "fehlercode",
        "fehlertext",
        "anfrageParameter"
    })
    public static class Fachdaten {

        protected String nachrichtID;
        protected String antwortID;
        @XmlElement(required = true)
        protected CodeZPOFehlercode fehlercode;
        protected String fehlertext;
        @XmlElement(name = "anfrage.parameter")
        protected String anfrageParameter;

        /**
         * Gets the value of the nachrichtID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNachrichtID() {
            return nachrichtID;
        }

        /**
         * Sets the value of the nachrichtID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNachrichtID(String value) {
            this.nachrichtID = value;
        }

        /**
         * Gets the value of the antwortID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAntwortID() {
            return antwortID;
        }

        /**
         * Sets the value of the antwortID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAntwortID(String value) {
            this.antwortID = value;
        }

        /**
         * Gets the value of the fehlercode property.
         * 
         * @return
         *     possible object is
         *     {@link CodeZPOFehlercode }
         *     
         */
        public CodeZPOFehlercode getFehlercode() {
            return fehlercode;
        }

        /**
         * Sets the value of the fehlercode property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeZPOFehlercode }
         *     
         */
        public void setFehlercode(CodeZPOFehlercode value) {
            this.fehlercode = value;
        }

        /**
         * Gets the value of the fehlertext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFehlertext() {
            return fehlertext;
        }

        /**
         * Sets the value of the fehlertext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFehlertext(String value) {
            this.fehlertext = value;
        }

        /**
         * Gets the value of the anfrageParameter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnfrageParameter() {
            return anfrageParameter;
        }

        /**
         * Sets the value of the anfrageParameter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnfrageParameter(String value) {
            this.anfrageParameter = value;
        }

    }

}
