//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.GDS.Kommunikation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.GDS.Kommunikation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="telekommunikationsart" type="{http://www.xjustiz.de}Code.GDS.Telekommunikationsart"/>
 *         &lt;element name="telekommunikationszusatz" type="{http://www.xjustiz.de}Code.GDS.Telekommunikationszusatz" minOccurs="0"/>
 *         &lt;element name="verbindung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.GDS.Kommunikation", propOrder = {
    "telekommunikationsart",
    "telekommunikationszusatz",
    "verbindung"
})
public class TypeGDSKommunikation {

    @XmlElement(required = true)
    protected CodeGDSTelekommunikationsart telekommunikationsart;
    protected CodeGDSTelekommunikationszusatz telekommunikationszusatz;
    @XmlElement(required = true)
    protected String verbindung;

    /**
     * Gets the value of the telekommunikationsart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGDSTelekommunikationsart }
     *     
     */
    public CodeGDSTelekommunikationsart getTelekommunikationsart() {
        return telekommunikationsart;
    }

    /**
     * Sets the value of the telekommunikationsart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGDSTelekommunikationsart }
     *     
     */
    public void setTelekommunikationsart(CodeGDSTelekommunikationsart value) {
        this.telekommunikationsart = value;
    }

    /**
     * Gets the value of the telekommunikationszusatz property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGDSTelekommunikationszusatz }
     *     
     */
    public CodeGDSTelekommunikationszusatz getTelekommunikationszusatz() {
        return telekommunikationszusatz;
    }

    /**
     * Sets the value of the telekommunikationszusatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGDSTelekommunikationszusatz }
     *     
     */
    public void setTelekommunikationszusatz(CodeGDSTelekommunikationszusatz value) {
        this.telekommunikationszusatz = value;
    }

    /**
     * Gets the value of the verbindung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerbindung() {
        return verbindung;
    }

    /**
     * Sets the value of the verbindung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerbindung(String value) {
        this.verbindung = value;
    }

}
