//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Der Datentyp enth�lt n�here Informationen zum Datum und zum Feststeller der Buchungspr�fung.
 * 
 * <p>Java class for Type.KASSE.Buchungspruefung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.KASSE.Buchungspruefung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datum.pruefung" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="feststeller" type="{http://www.xjustiz.de}Type.GDS.Ref.Beteiligtennummer" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.KASSE.Buchungspruefung", propOrder = {
    "datumPruefung",
    "feststeller"
})
public class TypeKASSEBuchungspruefung {

    @XmlElement(name = "datum.pruefung")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datumPruefung;
    @XmlElement(required = true)
    protected List<TypeGDSRefBeteiligtennummer> feststeller;

    /**
     * Gets the value of the datumPruefung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPruefung() {
        return datumPruefung;
    }

    /**
     * Sets the value of the datumPruefung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPruefung(XMLGregorianCalendar value) {
        this.datumPruefung = value;
    }

    /**
     * Gets the value of the feststeller property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feststeller property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeststeller().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeGDSRefBeteiligtennummer }
     * 
     * 
     */
    public List<TypeGDSRefBeteiligtennummer> getFeststeller() {
        if (feststeller == null) {
            feststeller = new ArrayList<TypeGDSRefBeteiligtennummer>();
        }
        return this.feststeller;
    }

}
