//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Die Angabe einer zeitlichen Ausdehnung eines Ereignisses. Die L�nge einer Zeitspanne bzw. Zeitraums.
 * 
 * <p>Java class for Type.STRAF.Dauer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.STRAF.Dauer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jahr" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="monate" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="wochen" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="tage" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="stunden" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="minuten" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="sekunden" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="sonstige" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="tagessatzhoehe" type="{http://www.xjustiz.de}Type.GDS.Geldbetrag" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.STRAF.Dauer", propOrder = {
    "jahr",
    "monate",
    "wochen",
    "tage",
    "stunden",
    "minuten",
    "sekunden",
    "sonstige",
    "tagessatzhoehe"
})
public class TypeSTRAFDauer {

    protected String jahr;
    protected String monate;
    protected String wochen;
    protected String tage;
    protected String stunden;
    protected String minuten;
    protected String sekunden;
    protected String sonstige;
    protected TypeGDSGeldbetrag tagessatzhoehe;

    /**
     * Gets the value of the jahr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJahr() {
        return jahr;
    }

    /**
     * Sets the value of the jahr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJahr(String value) {
        this.jahr = value;
    }

    /**
     * Gets the value of the monate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonate() {
        return monate;
    }

    /**
     * Sets the value of the monate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonate(String value) {
        this.monate = value;
    }

    /**
     * Gets the value of the wochen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWochen() {
        return wochen;
    }

    /**
     * Sets the value of the wochen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWochen(String value) {
        this.wochen = value;
    }

    /**
     * Gets the value of the tage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTage() {
        return tage;
    }

    /**
     * Sets the value of the tage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTage(String value) {
        this.tage = value;
    }

    /**
     * Gets the value of the stunden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStunden() {
        return stunden;
    }

    /**
     * Sets the value of the stunden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStunden(String value) {
        this.stunden = value;
    }

    /**
     * Gets the value of the minuten property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinuten() {
        return minuten;
    }

    /**
     * Sets the value of the minuten property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinuten(String value) {
        this.minuten = value;
    }

    /**
     * Gets the value of the sekunden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSekunden() {
        return sekunden;
    }

    /**
     * Sets the value of the sekunden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSekunden(String value) {
        this.sekunden = value;
    }

    /**
     * Gets the value of the sonstige property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonstige() {
        return sonstige;
    }

    /**
     * Sets the value of the sonstige property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonstige(String value) {
        this.sonstige = value;
    }

    /**
     * Gets the value of the tagessatzhoehe property.
     * 
     * @return
     *     possible object is
     *     {@link TypeGDSGeldbetrag }
     *     
     */
    public TypeGDSGeldbetrag getTagessatzhoehe() {
        return tagessatzhoehe;
    }

    /**
     * Sets the value of the tagessatzhoehe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeGDSGeldbetrag }
     *     
     */
    public void setTagessatzhoehe(TypeGDSGeldbetrag value) {
        this.tagessatzhoehe = value;
    }

}
