//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp kann zur Angabe von Messergebnissen verwendet werden z.B. von Blutalkohol-Untersuchungen oder Geschwindigkeitsmessungen.
 * 
 * <p>Java class for Type.STRAF.Messung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.STRAF.Messung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messwert" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="einheit" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *         &lt;element name="gegenstand" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.STRAF.Messung", propOrder = {
    "messwert",
    "einheit",
    "gegenstand"
})
public class TypeSTRAFMessung {

    @XmlElement(required = true)
    protected String messwert;
    @XmlElement(required = true)
    protected String einheit;
    protected String gegenstand;

    /**
     * Gets the value of the messwert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesswert() {
        return messwert;
    }

    /**
     * Sets the value of the messwert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesswert(String value) {
        this.messwert = value;
    }

    /**
     * Gets the value of the einheit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEinheit() {
        return einheit;
    }

    /**
     * Sets the value of the einheit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEinheit(String value) {
        this.einheit = value;
    }

    /**
     * Gets the value of the gegenstand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGegenstand() {
        return gegenstand;
    }

    /**
     * Sets the value of the gegenstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGegenstand(String value) {
        this.gegenstand = value;
    }

}
