//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.VSTR.Gerichtsvollzieher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.VSTR.Gerichtsvollzieher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dienstbezeichnung" type="{http://www.xjustiz.de}Code.VSTR.Gerichtsvollzieher.Dienstbezeichnung"/>
 *         &lt;element name="vorname" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA"/>
 *         &lt;element name="name" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeA"/>
 *         &lt;element name="amtsgericht" type="{http://www.xjustiz.de}Code.GDS.Gerichte.Typ3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.VSTR.Gerichtsvollzieher", propOrder = {
    "dienstbezeichnung",
    "vorname",
    "name",
    "amtsgericht"
})
public class TypeVSTRGerichtsvollzieher {

    @XmlElement(required = true)
    protected CodeVSTRGerichtsvollzieherDienstbezeichnung dienstbezeichnung;
    @XmlElement(required = true)
    protected String vorname;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected CodeGDSGerichteTyp3 amtsgericht;

    /**
     * Gets the value of the dienstbezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link CodeVSTRGerichtsvollzieherDienstbezeichnung }
     *     
     */
    public CodeVSTRGerichtsvollzieherDienstbezeichnung getDienstbezeichnung() {
        return dienstbezeichnung;
    }

    /**
     * Sets the value of the dienstbezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeVSTRGerichtsvollzieherDienstbezeichnung }
     *     
     */
    public void setDienstbezeichnung(CodeVSTRGerichtsvollzieherDienstbezeichnung value) {
        this.dienstbezeichnung = value;
    }

    /**
     * Gets the value of the vorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorname() {
        return vorname;
    }

    /**
     * Sets the value of the vorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorname(String value) {
        this.vorname = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the amtsgericht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public CodeGDSGerichteTyp3 getAmtsgericht() {
        return amtsgericht;
    }

    /**
     * Sets the value of the amtsgericht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGDSGerichteTyp3 }
     *     
     */
    public void setAmtsgericht(CodeGDSGerichteTyp3 value) {
        this.amtsgericht = value;
    }

}
