//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Type.DABAG.Erbbaurecht complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Erbbaurecht">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="art" type="{http://www.xjustiz.de}Code.DABAG.Erbbaurechtsart"/>
 *         &lt;element name="veraeusserungsbeschraenkung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="veraeusserungsbeschraenkungAusnahme" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="belastungsbeschraenkung" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="belastungsbeschraenkungAusnahme" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="auswahl_befristung" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="dauer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                   &lt;element name="endtermin" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="belastung" type="{http://www.xjustiz.de}Type.DABAG.Ref.Belastung" maxOccurs="unbounded"/>
 *         &lt;element name="auswahl_grundbuchblatt" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="bestehendesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.Ref.Grundbuchblatt"/>
 *                   &lt;element name="neuesGrundbuchblatt">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="grundbuchbezirk" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
 *                             &lt;element name="grundbuchart" type="{http://www.xjustiz.de}Code.DABAG.Grundbuchart" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Erbbaurecht", propOrder = {
    "art",
    "veraeusserungsbeschraenkung",
    "veraeusserungsbeschraenkungAusnahme",
    "belastungsbeschraenkung",
    "belastungsbeschraenkungAusnahme",
    "auswahlBefristung",
    "belastung",
    "auswahlGrundbuchblatt"
})
public class TypeDABAGErbbaurecht {

    @XmlElement(required = true)
    protected CodeDABAGErbbaurechtsart art;
    protected String veraeusserungsbeschraenkung;
    protected String veraeusserungsbeschraenkungAusnahme;
    protected String belastungsbeschraenkung;
    protected String belastungsbeschraenkungAusnahme;
    @XmlElement(name = "auswahl_befristung")
    protected TypeDABAGErbbaurecht.AuswahlBefristung auswahlBefristung;
    @XmlElement(required = true)
    protected List<TypeDABAGRefBelastung> belastung;
    @XmlElement(name = "auswahl_grundbuchblatt")
    protected TypeDABAGErbbaurecht.AuswahlGrundbuchblatt auswahlGrundbuchblatt;

    /**
     * Gets the value of the art property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDABAGErbbaurechtsart }
     *     
     */
    public CodeDABAGErbbaurechtsart getArt() {
        return art;
    }

    /**
     * Sets the value of the art property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDABAGErbbaurechtsart }
     *     
     */
    public void setArt(CodeDABAGErbbaurechtsart value) {
        this.art = value;
    }

    /**
     * Gets the value of the veraeusserungsbeschraenkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVeraeusserungsbeschraenkung() {
        return veraeusserungsbeschraenkung;
    }

    /**
     * Sets the value of the veraeusserungsbeschraenkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVeraeusserungsbeschraenkung(String value) {
        this.veraeusserungsbeschraenkung = value;
    }

    /**
     * Gets the value of the veraeusserungsbeschraenkungAusnahme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVeraeusserungsbeschraenkungAusnahme() {
        return veraeusserungsbeschraenkungAusnahme;
    }

    /**
     * Sets the value of the veraeusserungsbeschraenkungAusnahme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVeraeusserungsbeschraenkungAusnahme(String value) {
        this.veraeusserungsbeschraenkungAusnahme = value;
    }

    /**
     * Gets the value of the belastungsbeschraenkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelastungsbeschraenkung() {
        return belastungsbeschraenkung;
    }

    /**
     * Sets the value of the belastungsbeschraenkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelastungsbeschraenkung(String value) {
        this.belastungsbeschraenkung = value;
    }

    /**
     * Gets the value of the belastungsbeschraenkungAusnahme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBelastungsbeschraenkungAusnahme() {
        return belastungsbeschraenkungAusnahme;
    }

    /**
     * Sets the value of the belastungsbeschraenkungAusnahme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBelastungsbeschraenkungAusnahme(String value) {
        this.belastungsbeschraenkungAusnahme = value;
    }

    /**
     * Gets the value of the auswahlBefristung property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGErbbaurecht.AuswahlBefristung }
     *     
     */
    public TypeDABAGErbbaurecht.AuswahlBefristung getAuswahlBefristung() {
        return auswahlBefristung;
    }

    /**
     * Sets the value of the auswahlBefristung property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGErbbaurecht.AuswahlBefristung }
     *     
     */
    public void setAuswahlBefristung(TypeDABAGErbbaurecht.AuswahlBefristung value) {
        this.auswahlBefristung = value;
    }

    /**
     * Gets the value of the belastung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the belastung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBelastung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGRefBelastung }
     * 
     * 
     */
    public List<TypeDABAGRefBelastung> getBelastung() {
        if (belastung == null) {
            belastung = new ArrayList<TypeDABAGRefBelastung>();
        }
        return this.belastung;
    }

    /**
     * Gets the value of the auswahlGrundbuchblatt property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGErbbaurecht.AuswahlGrundbuchblatt }
     *     
     */
    public TypeDABAGErbbaurecht.AuswahlGrundbuchblatt getAuswahlGrundbuchblatt() {
        return auswahlGrundbuchblatt;
    }

    /**
     * Sets the value of the auswahlGrundbuchblatt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGErbbaurecht.AuswahlGrundbuchblatt }
     *     
     */
    public void setAuswahlGrundbuchblatt(TypeDABAGErbbaurecht.AuswahlGrundbuchblatt value) {
        this.auswahlGrundbuchblatt = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="dauer" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *         &lt;element name="endtermin" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dauer",
        "endtermin"
    })
    public static class AuswahlBefristung {

        protected String dauer;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endtermin;

        /**
         * Gets the value of the dauer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDauer() {
            return dauer;
        }

        /**
         * Sets the value of the dauer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDauer(String value) {
            this.dauer = value;
        }

        /**
         * Gets the value of the endtermin property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndtermin() {
            return endtermin;
        }

        /**
         * Sets the value of the endtermin property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndtermin(XMLGregorianCalendar value) {
            this.endtermin = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="bestehendesGrundbuchblatt" type="{http://www.xjustiz.de}Type.DABAG.Ref.Grundbuchblatt"/>
     *         &lt;element name="neuesGrundbuchblatt">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="grundbuchbezirk" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
     *                   &lt;element name="grundbuchart" type="{http://www.xjustiz.de}Code.DABAG.Grundbuchart" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bestehendesGrundbuchblatt",
        "neuesGrundbuchblatt"
    })
    public static class AuswahlGrundbuchblatt {

        protected TypeDABAGRefGrundbuchblatt bestehendesGrundbuchblatt;
        protected TypeDABAGErbbaurecht.AuswahlGrundbuchblatt.NeuesGrundbuchblatt neuesGrundbuchblatt;

        /**
         * Gets the value of the bestehendesGrundbuchblatt property.
         * 
         * @return
         *     possible object is
         *     {@link TypeDABAGRefGrundbuchblatt }
         *     
         */
        public TypeDABAGRefGrundbuchblatt getBestehendesGrundbuchblatt() {
            return bestehendesGrundbuchblatt;
        }

        /**
         * Sets the value of the bestehendesGrundbuchblatt property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeDABAGRefGrundbuchblatt }
         *     
         */
        public void setBestehendesGrundbuchblatt(TypeDABAGRefGrundbuchblatt value) {
            this.bestehendesGrundbuchblatt = value;
        }

        /**
         * Gets the value of the neuesGrundbuchblatt property.
         * 
         * @return
         *     possible object is
         *     {@link TypeDABAGErbbaurecht.AuswahlGrundbuchblatt.NeuesGrundbuchblatt }
         *     
         */
        public TypeDABAGErbbaurecht.AuswahlGrundbuchblatt.NeuesGrundbuchblatt getNeuesGrundbuchblatt() {
            return neuesGrundbuchblatt;
        }

        /**
         * Sets the value of the neuesGrundbuchblatt property.
         * 
         * @param value
         *     allowed object is
         *     {@link TypeDABAGErbbaurecht.AuswahlGrundbuchblatt.NeuesGrundbuchblatt }
         *     
         */
        public void setNeuesGrundbuchblatt(TypeDABAGErbbaurecht.AuswahlGrundbuchblatt.NeuesGrundbuchblatt value) {
            this.neuesGrundbuchblatt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="grundbuchbezirk" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC"/>
         *         &lt;element name="grundbuchart" type="{http://www.xjustiz.de}Code.DABAG.Grundbuchart" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "grundbuchbezirk",
            "grundbuchart"
        })
        public static class NeuesGrundbuchblatt {

            @XmlElement(required = true)
            protected String grundbuchbezirk;
            protected CodeDABAGGrundbuchart grundbuchart;

            /**
             * Gets the value of the grundbuchbezirk property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrundbuchbezirk() {
                return grundbuchbezirk;
            }

            /**
             * Sets the value of the grundbuchbezirk property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrundbuchbezirk(String value) {
                this.grundbuchbezirk = value;
            }

            /**
             * Gets the value of the grundbuchart property.
             * 
             * @return
             *     possible object is
             *     {@link CodeDABAGGrundbuchart }
             *     
             */
            public CodeDABAGGrundbuchart getGrundbuchart() {
                return grundbuchart;
            }

            /**
             * Sets the value of the grundbuchart property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodeDABAGGrundbuchart }
             *     
             */
            public void setGrundbuchart(CodeDABAGGrundbuchart value) {
                this.grundbuchart = value;
            }

        }

    }

}
