//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Nacherbe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Nacherbe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nacherbe" type="{http://www.xjustiz.de}Type.DABAG.Eintragungsbeteiligter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Nacherbe", propOrder = {
    "nacherbe"
})
public class TypeDABAGNacherbe {

    @XmlElement(required = true)
    protected TypeDABAGEintragungsbeteiligter nacherbe;

    /**
     * Gets the value of the nacherbe property.
     * 
     * @return
     *     possible object is
     *     {@link TypeDABAGEintragungsbeteiligter }
     *     
     */
    public TypeDABAGEintragungsbeteiligter getNacherbe() {
        return nacherbe;
    }

    /**
     * Sets the value of the nacherbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeDABAGEintragungsbeteiligter }
     *     
     */
    public void setNacherbe(TypeDABAGEintragungsbeteiligter value) {
        this.nacherbe = value;
    }

}
