//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.DABAG.Niessbrauch.Berechtigter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.DABAG.Niessbrauch.Berechtigter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quote" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="zusatz" type="{urn:xoev-de:kosit:xoev:datentyp:din-spec-91379_2019-03}datatypeC" minOccurs="0"/>
 *         &lt;element name="niessbraucher" type="{http://www.xjustiz.de}Type.DABAG.Berechtigter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="eintragungsgrundlage" type="{http://www.xjustiz.de}Type.DABAG.Ref.Eintragungsgrundlage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.DABAG.Niessbrauch.Berechtigter", propOrder = {
    "quote",
    "zusatz",
    "niessbraucher",
    "eintragungsgrundlage"
})
public class TypeDABAGNiessbrauchBerechtigter {

    protected String quote;
    protected String zusatz;
    protected List<TypeDABAGBerechtigter> niessbraucher;
    protected List<TypeDABAGRefEintragungsgrundlage> eintragungsgrundlage;

    /**
     * Gets the value of the quote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuote() {
        return quote;
    }

    /**
     * Sets the value of the quote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuote(String value) {
        this.quote = value;
    }

    /**
     * Gets the value of the zusatz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZusatz() {
        return zusatz;
    }

    /**
     * Sets the value of the zusatz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZusatz(String value) {
        this.zusatz = value;
    }

    /**
     * Gets the value of the niessbraucher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the niessbraucher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNiessbraucher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGBerechtigter }
     * 
     * 
     */
    public List<TypeDABAGBerechtigter> getNiessbraucher() {
        if (niessbraucher == null) {
            niessbraucher = new ArrayList<TypeDABAGBerechtigter>();
        }
        return this.niessbraucher;
    }

    /**
     * Gets the value of the eintragungsgrundlage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eintragungsgrundlage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEintragungsgrundlage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeDABAGRefEintragungsgrundlage }
     * 
     * 
     */
    public List<TypeDABAGRefEintragungsgrundlage> getEintragungsgrundlage() {
        if (eintragungsgrundlage == null) {
            eintragungsgrundlage = new ArrayList<TypeDABAGRefEintragungsgrundlage>();
        }
        return this.eintragungsgrundlage;
    }

}
