//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.13 at 01:28:34 PM CEST 
//


package com.java.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Type.STRAF.BFJ.Fahrerlaubnis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Type.STRAF.BFJ.Fahrerlaubnis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="fahrerlaubnissperreBis" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="fahrerlaubnissperreFuerImmer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type.STRAF.BFJ.Fahrerlaubnis", propOrder = {
    "fahrerlaubnissperreBis",
    "fahrerlaubnissperreFuerImmer"
})
public class TypeSTRAFBFJFahrerlaubnis {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fahrerlaubnissperreBis;
    protected Boolean fahrerlaubnissperreFuerImmer;

    /**
     * Gets the value of the fahrerlaubnissperreBis property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFahrerlaubnissperreBis() {
        return fahrerlaubnissperreBis;
    }

    /**
     * Sets the value of the fahrerlaubnissperreBis property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFahrerlaubnissperreBis(XMLGregorianCalendar value) {
        this.fahrerlaubnissperreBis = value;
    }

    /**
     * Gets the value of the fahrerlaubnissperreFuerImmer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFahrerlaubnissperreFuerImmer() {
        return fahrerlaubnissperreFuerImmer;
    }

    /**
     * Sets the value of the fahrerlaubnissperreFuerImmer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFahrerlaubnissperreFuerImmer(Boolean value) {
        this.fahrerlaubnissperreFuerImmer = value;
    }

}
